%% R2C15：Gao published three-node topology 补充验证

clear;
clc;
close all;
yalmip('clear');
total_timer = tic;

%% ================================== 00 环境初始化 ==================================
validation_directory = fileparts(mfilename('fullpath'));
project_root = fileparts(validation_directory);
common_directory = fullfile(project_root, 'Common_Functions');
output_directory = fullfile(validation_directory, 'outputs');
original_path = path;
addpath(common_directory, validation_directory);
cleanup_path = onCleanup(@() path(original_path));

assert(exist('yalmip', 'file') == 2, '未找到 YALMIP。');
assert(exist('gurobi', 'file') ~= 0, '未找到 Gurobi MATLAB 接口。');
if ~isfolder(output_directory)
    mkdir(output_directory);
end

%% ================================== 01 场景设置 ==================================
method_names = ["M2", "M3", "M4", "M5"];
detail_table = table();
comparison_table = table();
audit_table = table();
scenario_results = cell(numel(method_names), 1);

%% ================================== 02 M2--M5 求解 ==================================
for method_index = 1:numel(method_names)
    method_name = method_names(method_index);
    scenario_output = fullfile(output_directory, lower(method_name));
    if ~isfolder(scenario_output)
        mkdir(scenario_output);
    end

    fprintf('\n================ R2C15 %s ================\n', method_name);
    scenario_timer = tic;
    cfg = prepare_r2c15_case(project_root, scenario_output, method_name);

    centralized_result = solve_stage1_centralized(cfg);
    if method_name == "M2"
        stage1_result = centralized_result;
        solution_source = "Independent M2";
        admm_iterations = NaN;
        admm_converged = NaN;
        admm_primal = NaN;
        admm_dual = NaN;
    else
        cfg.admm.maximum_wall_time_seconds = 1800;
        stage1_result = solve_stage1_admm(cfg);
        assert(stage1_result.converged, ...
            '%s ADMM 未收敛：%s。', method_name, ...
            stage1_result.termination_reason);
        solution_source = "ADMM";
        admm_iterations = stage1_result.iterations;
        admm_converged = double(stage1_result.converged);
        admm_primal = stage1_result.final_primal_residual;
        admm_dual = stage1_result.final_dual_residual;
    end

    [stage2_results, stage2_summary] = solve_all_stage2( ...
        cfg, stage1_result, char(method_name));
    current_audit = audit_r2c15_results( ...
        cfg, stage1_result, stage2_results, method_name);
    assert(current_audit.big_m_sufficient, ...
        '%s 成本 Big-M=%.3f 不充分，至少需要 %.3f。', ...
        method_name, cfg.stage2.big_m_cost, ...
        current_audit.maximum_required_big_m);

    scenario_wall_time = toc(scenario_timer);
    current_detail = table(method_name, solution_source, ...
        stage2_summary.total_operating_cost, ...
        stage2_summary.per_dcp_cost(1), ...
        stage2_summary.per_dcp_cost(2), ...
        stage2_summary.per_dcp_cost(3), ...
        stage1_result.total_physical_cost, scenario_wall_time, ...
        stage2_summary.maximum_single_dcp_mip_gap, ...
        admm_iterations, admm_converged, admm_primal, admm_dual, ...
        'VariableNames', {'Method', 'SolutionSource', 'TotalCost_USD', ...
        'DCP1Cost_USD', 'DCP2Cost_USD', 'DCP3Cost_USD', ...
        'Stage1PhysicalCost_USD', 'TotalRuntime_s', ...
        'MaximumStage2MIPGap', 'ADMMIterations', 'ADMMConverged', ...
        'ADMMFinalPrimalResidual', 'ADMMFinalDualResidual'});
    detail_table = [detail_table; current_detail]; %#ok<AGROW>

    total_stage1_error = 100 * abs( ...
        stage1_result.total_physical_cost - ...
        centralized_result.total_physical_cost) / ...
        max(abs(centralized_result.total_physical_cost), eps);
    per_dcp_error = 100 * abs( ...
        stage1_result.per_dc_cost - centralized_result.per_dc_cost) ./ ...
        max(abs(centralized_result.per_dc_cost), eps);
    current_comparison = table(method_name, ...
        centralized_result.total_physical_cost, ...
        stage1_result.total_physical_cost, total_stage1_error, ...
        max(per_dcp_error), 'VariableNames', {'Method', ...
        'CentralizedStage1Cost_USD', 'ReportedStage1Cost_USD', ...
        'TotalRelativeError_Percent', 'MaximumPerDCPError_Percent'});
    comparison_table = [comparison_table; current_comparison]; %#ok<AGROW>

    current_audit_row = table(method_name, ...
        current_audit.configured_big_m, ...
        current_audit.maximum_required_big_m, ...
        current_audit.big_m_margin, ...
        current_audit.big_m_sufficient, ...
        current_audit.maximum_workload_error, ...
        current_audit.maximum_storage_error, ...
        current_audit.maximum_power_error, ...
        current_audit.maximum_initial_soc_error, ...
        current_audit.maximum_disabled_flow, ...
        stage2_summary.all_solved, ...
        'VariableNames', {'Method', 'ConfiguredBigM_USD', ...
        'RequiredBigM_USD', 'BigMMargin_USD', 'BigMSufficient', ...
        'MaximumWorkloadAccountingError', ...
        'MaximumStorageBalanceError', 'MaximumPowerBalanceError', ...
        'MaximumInitialSOCError', 'MaximumDisabledFlow', 'AllSolved'});
    audit_table = [audit_table; current_audit_row]; %#ok<AGROW>

    scenario_results{method_index} = struct( ...
        'cfg', cfg, 'centralized_stage1', centralized_result, ...
        'stage1', stage1_result, 'stage2', {stage2_results}, ...
        'stage2_summary', stage2_summary, 'audit', current_audit);
    save(fullfile(scenario_output, 'scenario_result.mat'), ...
        'cfg', 'centralized_result', 'stage1_result', ...
        'stage2_results', 'stage2_summary', 'current_audit', '-v7.3');
    save(fullfile(output_directory, 'r2c15_checkpoint.mat'), ...
        'method_names', 'method_index', 'detail_table', ...
        'comparison_table', 'audit_table', 'scenario_results', '-v7.3');
end

%% ================================== 03 Response 表 ==================================
method_cost = detail_table.TotalCost_USD';
method_saving = 100 * (method_cost(1) - method_cost(2:4)) / method_cost(1);
response_table = table(method_cost(1), method_cost(2), method_cost(3), ...
    method_cost(4), method_saving(1), method_saving(2), method_saving(3), ...
    'VariableNames', {'M2TotalCost_USD', 'M3TotalCost_USD', ...
    'M4TotalCost_USD', 'M5TotalCost_USD', ...
    'M3SavingVsM2_Percent', 'M4SavingVsM2_Percent', ...
    'M5SavingVsM2_Percent'});

%% ================================== 04 保存结果 ==================================
writetable(response_table, fullfile(output_directory, ...
    'r2c15_response_table.csv'));
writetable(detail_table, fullfile(output_directory, ...
    'r2c15_per_dcp_results.csv'));
writetable(comparison_table, fullfile(output_directory, ...
    'r2c15_admm_centralized_comparison.csv'));
writetable(audit_table, fullfile(output_directory, ...
    'r2c15_big_m_audit.csv'));

total_wall_time_seconds = toc(total_timer);
save(fullfile(output_directory, 'r2c15_gao_3dcp_results.mat'), ...
    'method_names', 'response_table', 'detail_table', ...
    'comparison_table', 'audit_table', 'scenario_results', ...
    'total_wall_time_seconds', '-v7.3');

disp(response_table);
fprintf('\nR2C15 运行结束，总用时 %.2f s。\n', total_wall_time_seconds);
fprintf('结果目录：%s\n', output_directory);
