%% R2C4：Stage 2 代表性用户组可扩展性测试
% 使用最终基础版 ADMM Stage 1 结果，仅改变每个 DCP 的代表性用户组数量。

clear;
clc;

%% ================================== 00 路径与统一参数 ==================================
response_directory = fileparts(mfilename('fullpath'));
project_root = fileparts(response_directory);
common_directory = fullfile(project_root, 'Common_Functions');
output_directory = fullfile(response_directory, 'outputs');
original_path = path;
addpath(common_directory, response_directory);
cleanup_path = onCleanup(@() path(original_path));

cfg = prepare_case(project_root, output_directory);

% 用户组规模验证固定采用 4 档交互式延时与 3 档批处理延时，共 12 种组合。
% 在入口处显式设置，避免后续修改主算例档位时改变本验证的计算规模。
cfg.stage2.inter_delay_set = [0.05, 0.10, 0.15, 0.20];                         % 交互式延时，s
cfg.stage2.batch_delay_set = [1, 2, 4];                                       % 批处理延时，h

% R2C4 仅对 Stage 2 放宽 MIP gap，并启用 Gurobi 对称性处理。
cfg.stage2.solver = sdpsettings('solver', 'gurobi', 'verbose', 0, ...
    'gurobi.MIPGap', 1e-4, ...
    'gurobi.IntFeasTol', 1e-8, ...
    'gurobi.BarConvTol', 1e-9, ...
    'gurobi.Symmetry', 2, ...
    'savesolveroutput', 1);

%% ================================== 01 固定 Stage 1 结果 ==================================
paper_stage1_file = fullfile(project_root, ...
    'Paper_Case', 'outputs', 'admm_stage1.mat');
response_stage1_file = fullfile(project_root, ...
    'Response_R1C5_R2C2', 'outputs', 'admm_stage1.mat');

if isfile(paper_stage1_file)
    stage1_data = load(paper_stage1_file, 'result');
elseif isfile(response_stage1_file)
    stage1_data = load(response_stage1_file, 'result');
else
    fprintf('未找到已有 ADMM Stage 1 结果，当前入口将先求解一次 Stage 1。\n');
    stage1_data.result = solve_stage1_admm(cfg);
end
stage1_result = stage1_data.result;

%% ================================== 02 场景与结果容器 ==================================
user_group_counts = cfg.scalability.user_group_counts;
number_repetitions = cfg.scalability.number_repetitions;
number_scenario = numel(user_group_counts);
number_repeat_row = number_scenario * number_repetitions;
number_dcp_row = number_repeat_row * cfg.number_dc;

repeat_user_group = zeros(number_repeat_row, 1);
repeat_index = zeros(number_repeat_row, 1);
repeat_total_runtime = zeros(number_repeat_row, 1);
repeat_maximum_dcp_runtime = zeros(number_repeat_row, 1);
repeat_total_solver_time = zeros(number_repeat_row, 1);
repeat_maximum_mip_gap = nan(number_repeat_row, 1);
repeat_total_cost = zeros(number_repeat_row, 1);
repeat_maximum_accounting_error = zeros(number_repeat_row, 1);
repeat_all_solved = false(number_repeat_row, 1);

dcp_user_group = zeros(number_dcp_row, 1);
dcp_repeat_index = zeros(number_dcp_row, 1);
dcp_number = zeros(number_dcp_row, 1);
dcp_wall_time = zeros(number_dcp_row, 1);
dcp_solver_time = zeros(number_dcp_row, 1);
dcp_mip_gap = nan(number_dcp_row, 1);
dcp_cost = zeros(number_dcp_row, 1);
dcp_accounting_error = zeros(number_dcp_row, 1);
dcp_solver_status = strings(number_dcp_row, 1);
dcp_zero_inter_count = zeros(number_dcp_row, 1);
dcp_zero_batch_count = zeros(number_dcp_row, 1);
dcp_active_candidate_count = zeros(number_dcp_row, 1);
dcp_full_candidate_count = zeros(number_dcp_row, 1);
dcp_pairwise_constraint_count = zeros(number_dcp_row, 1);

%% ================================== 03 用户组规模循环 ==================================
repeat_row = 0;
dcp_row = 0;
for scenario_index = 1:number_scenario
    number_user_group = user_group_counts(scenario_index);

    for repetition = 1:number_repetitions
        repeat_row = repeat_row + 1;
        cfg_case = cfg;
        cfg_case.stage2.number_user_group = number_user_group;
        scenario_name = sprintf('%d groups/DCP, repetition %d/%d', ...
            number_user_group, repetition, number_repetitions);

        fprintf('\n================ %s ================\n', scenario_name);
        [~, single_summary] = solve_all_stage2_scalability( ...
            cfg_case, stage1_result, scenario_name);

        repeat_user_group(repeat_row) = number_user_group;
        repeat_index(repeat_row) = repetition;
        repeat_total_runtime(repeat_row) = single_summary.total_wall_time_seconds;
        repeat_maximum_dcp_runtime(repeat_row) = ...
            single_summary.maximum_single_dcp_wall_time_seconds;
        repeat_total_solver_time(repeat_row) = single_summary.total_solver_time_seconds;
        repeat_maximum_mip_gap(repeat_row) = single_summary.maximum_single_dcp_mip_gap;
        repeat_total_cost(repeat_row) = single_summary.total_end_to_end_cost;
        repeat_maximum_accounting_error(repeat_row) = ...
            single_summary.maximum_workload_accounting_error;
        repeat_all_solved(repeat_row) = single_summary.all_solved;

        for dc = 1:cfg.number_dc
            dcp_row = dcp_row + 1;
            dcp_user_group(dcp_row) = number_user_group;
            dcp_repeat_index(dcp_row) = repetition;
            dcp_number(dcp_row) = dc;
            dcp_wall_time(dcp_row) = single_summary.per_dcp_wall_time_seconds(dc);
            dcp_solver_time(dcp_row) = single_summary.per_dcp_solver_time_seconds(dc);
            dcp_mip_gap(dcp_row) = single_summary.per_dcp_mip_gap(dc);
            dcp_cost(dcp_row) = single_summary.per_dcp_cost(dc);
            dcp_accounting_error(dcp_row) = ...
                single_summary.per_dcp_accounting_error(dc);
            dcp_solver_status(dcp_row) = single_summary.per_dcp_status(dc);
            dcp_zero_inter_count(dcp_row) = ...
                single_summary.per_dcp_zero_inter_count(dc);
            dcp_zero_batch_count(dcp_row) = ...
                single_summary.per_dcp_zero_batch_count(dc);
            dcp_active_candidate_count(dcp_row) = ...
                single_summary.per_dcp_active_candidate_count(dc);
            dcp_full_candidate_count(dcp_row) = ...
                single_summary.per_dcp_full_candidate_count(dc);
            dcp_pairwise_constraint_count(dcp_row) = ...
                single_summary.per_dcp_pairwise_constraint_count(dc);
        end

        % 每完成一次重复即保存 checkpoint，避免长规模算例中断后丢失已完成数据。
        checkpoint_file = fullfile(cfg.output_directory, ...
            'r2c4_user_scalability_checkpoint.mat');
        save(checkpoint_file, 'cfg', 'repeat_row', 'dcp_row', ...
            'repeat_user_group', 'repeat_index', 'repeat_total_runtime', ...
            'repeat_maximum_dcp_runtime', 'repeat_total_solver_time', ...
            'repeat_maximum_mip_gap', 'repeat_total_cost', ...
            'repeat_maximum_accounting_error', 'repeat_all_solved', ...
            'dcp_user_group', 'dcp_repeat_index', 'dcp_number', ...
            'dcp_wall_time', 'dcp_solver_time', 'dcp_mip_gap', 'dcp_cost', ...
            'dcp_accounting_error', 'dcp_solver_status', ...
            'dcp_zero_inter_count', 'dcp_zero_batch_count', ...
            'dcp_active_candidate_count', 'dcp_full_candidate_count', ...
            'dcp_pairwise_constraint_count', '-v7.3');
    end
end

%% ================================== 04 重复试验表 ==================================
repeat_table = table( ...
    repeat_user_group, repeat_index, repeat_total_runtime, ...
    repeat_maximum_dcp_runtime, repeat_total_solver_time, ...
    repeat_maximum_mip_gap, repeat_total_cost, ...
    repeat_maximum_accounting_error, repeat_all_solved, ...
    'VariableNames', { ...
    'UserGroupsPerDCP', ...
    'Repetition', ...
    'TotalStage2Runtime_s', ...
    'MaximumSingleDCPRuntime_s', ...
    'TotalGurobiSolverTime_s', ...
    'MaximumMIPGap', ...
    'Stage2EndToEndCost_USD', ...
    'MaximumWorkloadAccountingError', ...
    'AllSolved'});

per_dcp_table = table( ...
    dcp_user_group, dcp_repeat_index, dcp_number, dcp_wall_time, ...
    dcp_solver_time, dcp_mip_gap, dcp_cost, dcp_accounting_error, ...
    dcp_solver_status, dcp_zero_inter_count, dcp_zero_batch_count, ...
    dcp_active_candidate_count, dcp_full_candidate_count, ...
    dcp_pairwise_constraint_count, ...
    'VariableNames', { ...
    'UserGroupsPerDCP', ...
    'Repetition', ...
    'DCP', ...
    'WallTime_s', ...
    'GurobiSolverTime_s', ...
    'MIPGap', ...
    'EndToEndCost_USD', ...
    'WorkloadAccountingError', ...
    'SolverStatus', ...
    'ZeroInteractiveUserPeriods', ...
    'ZeroBatchUserPeriods', ...
    'ActiveCandidateCount', ...
    'FullCandidateCount', ...
    'PairwiseOptimalityConstraintCount'});

%% ================================== 05 汇总表 ==================================
number_combination = numel(cfg.stage2.inter_delay_set) * ...
    numel(cfg.stage2.batch_delay_set);
number_binary_variable = zeros(number_scenario, 1);
number_declared_variable = zeros(number_scenario, 1);
median_total_runtime = zeros(number_scenario, 1);
median_maximum_dcp_runtime = zeros(number_scenario, 1);
median_total_solver_time = zeros(number_scenario, 1);
maximum_mip_gap = zeros(number_scenario, 1);
median_total_cost = zeros(number_scenario, 1);
maximum_accounting_error = zeros(number_scenario, 1);
all_solved = false(number_scenario, 1);

for scenario_index = 1:number_scenario
    number_user_group = user_group_counts(scenario_index);
    rows = repeat_user_group == number_user_group;

    number_binary_variable(scenario_index) = number_user_group * ( ...
        number_combination * cfg.number_period + cfg.number_period^2);
    number_declared_variable(scenario_index) = 2448 * number_user_group + 289;
    median_total_runtime(scenario_index) = median(repeat_total_runtime(rows));
    median_maximum_dcp_runtime(scenario_index) = ...
        median(repeat_maximum_dcp_runtime(rows));
    median_total_solver_time(scenario_index) = median(repeat_total_solver_time(rows));
    maximum_mip_gap(scenario_index) = max(repeat_maximum_mip_gap(rows));
    median_total_cost(scenario_index) = median(repeat_total_cost(rows));
    maximum_accounting_error(scenario_index) = ...
        max(repeat_maximum_accounting_error(rows));
    all_solved(scenario_index) = all(repeat_all_solved(rows));
end

two_group_row = find(user_group_counts == 2, 1);
two_group_reference_error = 100 * abs( ...
    median_total_cost(two_group_row) - cfg.scalability.reference_two_group_cost) / ...
    abs(cfg.scalability.reference_two_group_cost);

summary_table = table( ...
    user_group_counts(:), number_binary_variable, number_declared_variable, ...
    median_total_runtime, median_maximum_dcp_runtime, ...
    median_total_solver_time, maximum_mip_gap, median_total_cost, ...
    maximum_accounting_error, all_solved, ...
    'VariableNames', { ...
    'UserGroupsPerDCP', ...
    'NumberBinaryVariablesPerDCP', ...
    'NumberDeclaredVariablesPerDCP', ...
    'MedianTotalStage2Runtime_s', ...
    'MedianMaximumSingleDCPRuntime_s', ...
    'MedianTotalGurobiSolverTime_s', ...
    'MaximumMIPGap', ...
    'MedianStage2EndToEndCost_USD', ...
    'MaximumWorkloadAccountingError', ...
    'AllSolved'});

%% ================================== 06 验收与导出 ==================================
assert(all(all_solved), '至少一个 R2C4 Stage 2 算例未正常求解。');
assert(all(maximum_accounting_error <= cfg.scalability.accounting_tolerance), ...
    '至少一个 R2C4 算例的用户组负载未闭合。');
assert(two_group_reference_error <= ...
    cfg.scalability.reference_cost_tolerance_percent, ...
    '2 用户组场景与最终基础版基准偏差 %.3e%%，超过允许阈值。', ...
    two_group_reference_error);

export_r2c4_results(cfg, summary_table, repeat_table, per_dcp_table);

disp(summary_table);
fprintf('2 用户组场景相对最终基础版基准成本偏差：%.3e%%\n', ...
    two_group_reference_error);
