%% R2C5：固定 day-ahead sharing plan 的 forecast perturbation test

clear;
clc;
close all;
yalmip('clear');
total_timer = tic;

%% ================================== 00 环境初始化 ==================================
validation_directory = fileparts(mfilename('fullpath'));
project_root = fileparts(validation_directory);
common_directory = fullfile(project_root, 'Common_Functions');
output_directory = fullfile(validation_directory, 'outputs');
original_path = path;
addpath(common_directory, validation_directory);
cleanup_path = onCleanup(@() path(original_path));

assert(exist('yalmip', 'file') == 2, '未找到 YALMIP。');
assert(exist('gurobi', 'file') ~= 0, '未找到 Gurobi MATLAB 接口。');
if ~isfolder(output_directory)
    mkdir(output_directory);
end

%% ================================== 01 参数设置 ==================================
perturbation_factors = [-0.10, -0.05, 0, 0.05, 0.10];
method_names = ["M2", "M5"];
number_method = numel(method_names);
day_ahead = cell(number_method, 1);
detail_table = table();
big_m_audit_table = table();
scenario_results = cell(numel(perturbation_factors), number_method);

%% ================================== 02 Nominal day-ahead 计划 ==================================
for method_index = 1:number_method
    method_name = method_names(method_index);
    nominal_output = fullfile(output_directory, ...
        sprintf('nominal_%s', lower(method_name)));
    if ~isfolder(nominal_output)
        mkdir(nominal_output);
    end
    cfg_nominal = prepare_r2c5_case( ...
        project_root, nominal_output, 0, method_name);

    fprintf('\n================ R2C5 nominal %s ================\n', method_name);
    if method_name == "M2"
        stage1_nominal = solve_stage1_centralized(cfg_nominal);
        solution_source = "Independent M2";
    else
        cfg_nominal.admm.maximum_wall_time_seconds = 1800;
        stage1_nominal = solve_stage1_admm(cfg_nominal);
        assert(stage1_nominal.converged, ...
            'R2C5 nominal M5 ADMM 未收敛：%s。', ...
            stage1_nominal.termination_reason);
        solution_source = "ADMM";
    end
    [stage2_nominal, stage2_nominal_summary] = solve_all_stage2( ...
        cfg_nominal, stage1_nominal, char(method_name + " nominal"));

    day_ahead{method_index} = struct( ...
        'cfg', cfg_nominal, 'stage1', stage1_nominal, ...
        'stage2', {stage2_nominal}, ...
        'stage2_summary', stage2_nominal_summary, ...
        'solution_source', solution_source);
    save(fullfile(nominal_output, 'day_ahead_result.mat'), ...
        'cfg_nominal', 'stage1_nominal', 'stage2_nominal', ...
        'stage2_nominal_summary', 'solution_source', '-v7.3');
end

%% ================================== 03 Realized local recourse ==================================
for factor_index = 1:numel(perturbation_factors)
    perturbation_factor = perturbation_factors(factor_index);
    for method_index = 1:number_method
        method_name = method_names(method_index);
        scenario_name = sprintf('%s_xi_%+.2f', method_name, ...
            perturbation_factor);
        scenario_output = fullfile(output_directory, ...
            sprintf('%02d_%s', ...
            (factor_index - 1) * number_method + method_index, ...
            lower(strrep(scenario_name, '+', 'p'))));
        if ~isfolder(scenario_output)
            mkdir(scenario_output);
        end

        fprintf('\n================ R2C5 %s ================\n', scenario_name);
        scenario_timer = tic;
        cfg_realized = prepare_r2c5_case(project_root, scenario_output, ...
            perturbation_factor, method_name);
        [realized_stage1, plan_audit] = build_r2c5_realized_plan( ...
            cfg_realized, day_ahead{method_index}.stage1);
        current_big_m_audit = audit_r2c5_big_m( ...
            cfg_realized, realized_stage1, scenario_name);
        big_m_audit_table = [ ...
            big_m_audit_table; current_big_m_audit]; %#ok<AGROW>

        [stage2_results, stage2_summary] = solve_all_stage2_recourse( ...
            cfg_realized, realized_stage1, ...
            day_ahead{method_index}.stage2, scenario_name);
        scenario_wall_time = toc(scenario_timer);

        simultaneous_grid = max(cellfun(@(item) max(min( ...
            item.p_grid_buy, item.p_grid_sell)), stage2_results));
        current_row = table(perturbation_factor, method_name, ...
            day_ahead{method_index}.solution_source, ...
            stage2_summary.total_operating_cost, ...
            stage2_summary.per_dcp_cost(1), ...
            stage2_summary.per_dcp_cost(2), ...
            stage2_summary.per_dcp_cost(3), ...
            stage2_summary.per_dcp_cost(4), ...
            stage2_summary.per_dcp_cost(5), ...
            stage2_summary.total_imbalance_cost, ...
            plan_audit.curtailed_task_export, ...
            plan_audit.number_clipped_source_period, ...
            plan_audit.maximum_power_plan_deviation, ...
            simultaneous_grid, ...
            stage2_summary.maximum_power_balance_error, ...
            stage2_summary.maximum_single_dcp_mip_gap, ...
            scenario_wall_time, stage2_summary.all_solved, ...
            'VariableNames', {'PerturbationFactor', 'Method', ...
            'DayAheadSolutionSource', 'TotalCost_USD', ...
            'DCP1Cost_USD', 'DCP2Cost_USD', 'DCP3Cost_USD', ...
            'DCP4Cost_USD', 'DCP5Cost_USD', ...
            'GridImbalanceCost_USD', 'CurtailedTaskMigration', ...
            'ClippedSourcePeriods', 'MaximumPowerPlanDeviation_kW', ...
            'MaximumSimultaneousGridBuySell_kW', ...
            'MaximumPowerBalanceError', 'MaximumStage2MIPGap', ...
            'Runtime_s', 'AllSolved'});
        detail_table = [detail_table; current_row]; %#ok<AGROW>

        scenario_results{factor_index, method_index} = struct( ...
            'cfg', cfg_realized, 'stage1', realized_stage1, ...
            'stage2', {stage2_results}, 'stage2_summary', stage2_summary, ...
            'plan_audit', plan_audit, 'big_m_audit', current_big_m_audit);
        save(fullfile(scenario_output, 'scenario_result.mat'), ...
            'cfg_realized', 'realized_stage1', 'stage2_results', ...
            'stage2_summary', 'plan_audit', ...
            'current_big_m_audit', '-v7.3');
        save(fullfile(output_directory, 'r2c5_checkpoint.mat'), ...
            'perturbation_factors', 'method_names', ...
            'factor_index', 'method_index', 'day_ahead', ...
            'detail_table', 'big_m_audit_table', ...
            'scenario_results', '-v7.3');
    end
end

%% ================================== 04 Response 汇总 ==================================
number_factor = numel(perturbation_factors);
m2_cost = zeros(number_factor, 1);
m5_cost = zeros(number_factor, 1);
for index = 1:number_factor
    factor = perturbation_factors(index);
    m2_row = detail_table(abs(detail_table.PerturbationFactor - factor) < ...
        1e-12 & detail_table.Method == "M2", :);
    m5_row = detail_table(abs(detail_table.PerturbationFactor - factor) < ...
        1e-12 & detail_table.Method == "M5", :);
    m2_cost(index) = m2_row.TotalCost_USD;
    m5_cost(index) = m5_row.TotalCost_USD;
end
cooperative_saving = 100 * (m2_cost - m5_cost) ./ m2_cost;
nominal_m5_cost = m5_cost(abs(perturbation_factors) < 1e-12);
m5_change = 100 * (m5_cost - nominal_m5_cost) / nominal_m5_cost;
response_table = table(perturbation_factors(:), m2_cost, m5_cost, ...
    cooperative_saving, m5_change, ...
    'VariableNames', {'PerturbationFactor', 'M2Cost_USD', ...
    'M5Cost_USD', 'SavingVsM2_Percent', ...
    'M5CostChangeFromNominal_Percent'});

%% ================================== 05 保存结果 ==================================
writetable(response_table, fullfile(output_directory, ...
    'r2c5_response_table.csv'));
writetable(detail_table, fullfile(output_directory, ...
    'r2c5_out_of_sample_details.csv'));
writetable(big_m_audit_table, fullfile(output_directory, ...
    'r2c5_big_m_audit.csv'));
total_wall_time_seconds = toc(total_timer);
save(fullfile(output_directory, 'r2c5_out_of_sample_results.mat'), ...
    'perturbation_factors', 'method_names', 'day_ahead', ...
    'response_table', 'detail_table', 'big_m_audit_table', ...
    'scenario_results', 'total_wall_time_seconds', '-v7.3');

disp(response_table);
fprintf('\nR2C5 运行结束，总用时 %.2f s。\n', total_wall_time_seconds);
fprintf('结果目录：%s\n', output_directory);
