function result = solve_stage2_recourse( ...
        cfg, dc, stage1_result, day_ahead_result)
%SOLVE_STAGE2_RECOURSE 求解含购售电偏差结算的单 DCP realized Stage 2。

%% ================================== 00 两类代表性用户组 ==================================
[workload_inter, workload_batch] = split_representative_groups( ...
    cfg, dc, stage1_result);

number_user_group = 2;
number_period = cfg.number_period;
inter_delay_set = cfg.stage2.inter_delay_set;
batch_delay_set = cfg.stage2.batch_delay_set;
[inter_delay_grid, batch_delay_grid] = ndgrid( ...
    inter_delay_set, batch_delay_set);
inter_delay_candidate = inter_delay_grid(:);
batch_delay_candidate = batch_delay_grid(:);
number_combination = numel(inter_delay_candidate);
delta_inter_candidate = inter_delay_candidate - ...
    cfg.time_tolerance_inter_original;
delta_batch_candidate = batch_delay_candidate - ...
    cfg.time_tolerance_batch_original;

coefficient_inter = cfg.stage2.inconvenience_inter(dc) * ...
    ones(number_user_group, 1);
coefficient_batch = cfg.stage2.inconvenience_batch(dc) * ...
    ones(number_user_group, 1);
gamma_inter_lower = ...
    cfg.stage2.gamma_inter_lower_factor * coefficient_inter;
gamma_inter_upper = ...
    cfg.stage2.gamma_inter_upper_factor * coefficient_inter;
gamma_batch_lower = ...
    cfg.stage2.gamma_batch_lower_factor * coefficient_batch;
gamma_batch_upper = ...
    cfg.stage2.gamma_batch_upper_factor * coefficient_batch;

%% ================================== 01 决策变量 ==================================
yalmip('clear');
select_combination = binvar(number_user_group, number_combination, ...
    number_period, 'full');
gamma_inter = sdpvar(number_user_group, number_period, 'full');
gamma_batch = sdpvar(number_user_group, number_period, 'full');
omega_inter = sdpvar(number_user_group, number_combination, ...
    number_period, 'full');
omega_batch = sdpvar(number_user_group, number_combination, ...
    number_period, 'full');
net_cost_candidate = sdpvar(number_user_group, number_combination, ...
    number_period, 'full');
selected_inter_delay = sdpvar(number_user_group, number_period, 'full');
selected_batch_delay = sdpvar(number_user_group, number_period, 'full');
batch_window_active = binvar(number_user_group, number_period, ...
    number_period, 'full');
delta_batch = sdpvar(number_user_group, number_period, ...
    number_period, 'full');
adjusted_batch = sdpvar(number_user_group, number_period, 'full');
server_inter_group = sdpvar(number_user_group, number_period, 'full');
server_batch = sdpvar(1, number_period, 'full');
server_total = sdpvar(1, number_period, 'full');
p_it = sdpvar(1, number_period, 'full');
p_dc_load = sdpvar(1, number_period, 'full');
p_grid = sdpvar(1, number_period, 'full');
p_grid_buy = sdpvar(1, number_period, 'full');
p_grid_sell = sdpvar(1, number_period, 'full');
p_pv = sdpvar(1, number_period, 'full');
p_wind = sdpvar(1, number_period, 'full');
p_charge = sdpvar(1, number_period, 'full');
p_discharge = sdpvar(1, number_period, 'full');
soc = sdpvar(1, number_period + 1, 'full');

% 实际购售电量相对 day-ahead 计划的四类非负偏差量，kW。
grid_buy_up = sdpvar(1, number_period, 'full');
grid_buy_down = sdpvar(1, number_period, 'full');
grid_sell_up = sdpvar(1, number_period, 'full');
grid_sell_down = sdpvar(1, number_period, 'full');

constraints = [];

%% ================================== 02 档位与精确线性化 ==================================
for user_group = 1:number_user_group
    constraints = [constraints, ...
        gamma_inter(user_group, :) >= gamma_inter_lower(user_group), ...
        gamma_inter(user_group, :) <= gamma_inter_upper(user_group), ...
        gamma_batch(user_group, :) >= gamma_batch_lower(user_group), ...
        gamma_batch(user_group, :) <= gamma_batch_upper(user_group)]; %#ok<AGROW>

    for t = 1:number_period
        constraints = [constraints, ...
            sum(select_combination(user_group, :, t)) == 1, ...
            selected_inter_delay(user_group, t) == ...
                select_combination(user_group, :, t) * ...
                inter_delay_candidate, ...
            selected_batch_delay(user_group, t) == ...
                select_combination(user_group, :, t) * ...
                batch_delay_candidate]; %#ok<AGROW>

        for combination = 1:number_combination
            selected = select_combination(user_group, combination, t);
            omega_i = omega_inter(user_group, combination, t);
            omega_b = omega_batch(user_group, combination, t);
            gamma_i = gamma_inter(user_group, t);
            gamma_b = gamma_batch(user_group, t);

            constraints = [constraints, ...
                omega_i >= gamma_inter_lower(user_group) * selected, ...
                omega_i <= gamma_inter_upper(user_group) * selected, ...
                omega_i >= gamma_i - gamma_inter_upper(user_group) * (1 - selected), ...
                omega_i <= gamma_i - gamma_inter_lower(user_group) * (1 - selected), ...
                omega_b >= gamma_batch_lower(user_group) * selected, ...
                omega_b <= gamma_batch_upper(user_group) * selected, ...
                omega_b >= gamma_b - gamma_batch_upper(user_group) * (1 - selected), ...
                omega_b <= gamma_b - gamma_batch_lower(user_group) * (1 - selected)]; %#ok<AGROW>

            inconvenience = ...
                coefficient_inter(user_group) * workload_inter(user_group, t) * ...
                    delta_inter_candidate(combination)^2 + ...
                coefficient_batch(user_group) * workload_batch(user_group, t) * ...
                    delta_batch_candidate(combination)^2;
            alternative_payment = ...
                gamma_i * delta_inter_candidate(combination) * ...
                    workload_inter(user_group, t) + ...
                gamma_b * delta_batch_candidate(combination) * ...
                    workload_batch(user_group, t);
            constraints = [constraints, ...
                net_cost_candidate(user_group, combination, t) == ...
                    inconvenience - alternative_payment]; %#ok<AGROW>
        end
    end
end

%% ================================== 03 用户最优档位 ==================================
big_m_cost = cfg.stage2.big_m_cost;
for user_group = 1:number_user_group
    for t = 1:number_period
        for selected_index = 1:number_combination
            for alternative_index = 1:number_combination
                if selected_index ~= alternative_index
                    constraints = [constraints, ...
                        net_cost_candidate(user_group, selected_index, t) <= ...
                        net_cost_candidate(user_group, alternative_index, t) + ...
                        big_m_cost * (1 - select_combination( ...
                        user_group, selected_index, t))]; %#ok<AGROW>
                end
            end
        end
    end
end

%% ================================== 04 批处理时间窗口 ==================================
big_m_time = cfg.stage2.big_m_time;
for user_group = 1:number_user_group
    for source_time = 1:number_period
        for destination_time = 1:number_period
            if destination_time == source_time
                constraints = [constraints, ...
                    batch_window_active(user_group, source_time, destination_time) == 0, ...
                    delta_batch(user_group, source_time, destination_time) >= ...
                        -workload_batch(user_group, source_time), ...
                    delta_batch(user_group, source_time, destination_time) <= 0]; %#ok<AGROW>
            elseif destination_time > source_time
                active = batch_window_active( ...
                    user_group, source_time, destination_time);
                shift = delta_batch(user_group, source_time, destination_time);
                constraints = [constraints, ...
                    destination_time <= source_time + ...
                        selected_batch_delay(user_group, source_time) + ...
                        big_m_time * (1 - active), ...
                    shift >= 0, ...
                    shift <= workload_batch(user_group, source_time) * active]; %#ok<AGROW>
            else
                constraints = [constraints, ...
                    batch_window_active(user_group, source_time, destination_time) == 0, ...
                    delta_batch(user_group, source_time, destination_time) == 0]; %#ok<AGROW>
            end
        end
        constraints = [constraints, ...
            sum(delta_batch(user_group, source_time, :), 3) == 0]; %#ok<AGROW>
    end

    for destination_time = 1:number_period
        constraints = [constraints, ...
            adjusted_batch(user_group, destination_time) == ...
                workload_batch(user_group, destination_time) + ...
                sum(delta_batch(user_group, :, destination_time), 2), ...
            adjusted_batch(user_group, destination_time) >= 0]; %#ok<AGROW>
    end
end

%% ================================== 05 用户补偿 ==================================
payment_inter = 0;
payment_batch = 0;
for user_group = 1:number_user_group
    for t = 1:number_period
        for combination = 1:number_combination
            payment_inter = payment_inter + ...
                omega_inter(user_group, combination, t) * ...
                delta_inter_candidate(combination) * ...
                workload_inter(user_group, t);
            payment_batch = payment_batch + ...
                omega_batch(user_group, combination, t) * ...
                delta_batch_candidate(combination) * ...
                workload_batch(user_group, t);
        end
    end
end
payment = payment_inter + payment_batch;

%% ================================== 06 服务器与 IT 功率 ==================================
server_inter_candidate = zeros( ...
    number_user_group, number_combination, number_period);
for user_group = 1:number_user_group
    for combination = 1:number_combination
        service_margin = cfg.processing_speed_server - ...
            1 / inter_delay_candidate(combination);
        server_inter_candidate(user_group, combination, :) = reshape(ceil( ...
            workload_inter(user_group, :) / service_margin), ...
            1, 1, number_period);
    end
end

for user_group = 1:number_user_group
    for t = 1:number_period
        candidate_servers = reshape( ...
            server_inter_candidate(user_group, :, t), ...
            number_combination, 1);
        constraints = [constraints, ...
            server_inter_group(user_group, t) == ...
                select_combination(user_group, :, t) * candidate_servers, ...
            server_inter_group(user_group, t) >= 0, ...
            server_inter_group(user_group, t) <= cfg.number_server]; %#ok<AGROW>
    end
end

for t = 1:number_period
    total_batch_workload = sum(adjusted_batch(:, t));
    total_inter_workload = sum(workload_inter(:, t));
    minimum_batch_servers = ...
        total_batch_workload / cfg.processing_speed_server;
    constraints = [constraints, ...
        server_batch(t) >= minimum_batch_servers, ...
        server_batch(t) <= minimum_batch_servers + 1, ...
        server_batch(t) >= 0, ...
        server_batch(t) <= cfg.number_server, ...
        server_total(t) >= ...
            sum(server_inter_group(:, t)) + server_batch(t), ...
        server_total(t) >= 0, ...
        server_total(t) <= cfg.number_server, ...
        p_it(t) == cfg.p_idle * server_total(t) + ...
            (cfg.p_peak - cfg.p_idle) / cfg.processing_speed_server * ...
            (total_batch_workload + total_inter_workload), ...
        p_dc_load(t) == cfg.dcp(dc).pue * p_it(t)]; %#ok<AGROW>
end

%% ================================== 07 本地能源与固定电力交互 ==================================
net_power_import = calculate_net_power_import( ...
    cfg, dc, stage1_result.consensus_flow);

constraints = [constraints, ...
    p_grid_buy >= 0, p_grid_sell >= 0, ...
    p_grid == p_grid_buy - p_grid_sell, ...
    p_grid >= cfg.p_grid_lower, p_grid <= cfg.p_grid_upper];

if cfg.dcp(dc).has_energy
    constraints = [constraints, soc(1) == cfg.soc_initial];
    for t = 1:number_period
        constraints = [constraints, ...
            p_pv(t) >= 0, p_pv(t) <= cfg.dcp(dc).p_pv_max(t), ...
            p_wind(t) >= 0, p_wind(t) <= cfg.dcp(dc).p_wind_max(t), ...
            p_charge(t) >= 0, p_charge(t) <= cfg.p_charge_max, ...
            p_discharge(t) >= 0, p_discharge(t) <= cfg.p_discharge_max, ...
            soc(t + 1) == soc(t) + ...
                cfg.eta_charge * p_charge(t) - ...
                p_discharge(t) / cfg.eta_discharge, ...
            soc(t + 1) >= 0, soc(t + 1) <= cfg.e_max, ...
            p_grid(t) + p_pv(t) + p_wind(t) + ...
                p_discharge(t) - p_charge(t) + net_power_import(t) == ...
                p_dc_load(t)]; %#ok<AGROW>
    end
else
    constraints = [constraints, ...
        p_grid == p_dc_load, p_pv == 0, p_wind == 0, ...
        p_charge == 0, p_discharge == 0, soc == 0];
end

%% ================================== 08 购售电偏差结算 ==================================
day_ahead_buy = day_ahead_result.p_grid_buy;
day_ahead_sell = day_ahead_result.p_grid_sell;
constraints = [constraints, ...
    grid_buy_up >= 0, grid_buy_down >= 0, ...
    grid_sell_up >= 0, grid_sell_down >= 0, ...
    p_grid_buy == day_ahead_buy + grid_buy_up - grid_buy_down, ...
    p_grid_sell == day_ahead_sell + grid_sell_up - grid_sell_down];

alpha = cfg.response.imbalance_penalty_factor;
price_buy = cfg.dcp(dc).price_ele;
price_sell = cfg.price_tariff;

cost_purchase_day_ahead = sum(price_buy .* day_ahead_buy * 1e-3);
cost_purchase_deviation = sum( ...
    (1 + alpha) * price_buy .* grid_buy_up * 1e-3 - ...
    (1 - alpha) * price_buy .* grid_buy_down * 1e-3);
cost_purchase = cost_purchase_day_ahead + cost_purchase_deviation;

revenue_sell_day_ahead = sum(price_sell .* day_ahead_sell * 1e-3);
revenue_sell_deviation = sum( ...
    (1 - alpha) * price_sell .* grid_sell_up * 1e-3 - ...
    (1 + alpha) * price_sell .* grid_sell_down * 1e-3);
revenue_sell = revenue_sell_day_ahead + revenue_sell_deviation;

base_realized_grid_cost = sum( ...
    price_buy .* p_grid_buy * 1e-3 - ...
    price_sell .* p_grid_sell * 1e-3);
settled_grid_cost = cost_purchase - revenue_sell;
cost_grid_imbalance = settled_grid_cost - base_realized_grid_cost;

%% ================================== 09 目标函数与求解 ==================================
cost_carbon = sum( ...
    cfg.dcp(dc).carbon_eleprice * p_grid_buy * 1e-3);
cost_storage = sum(cfg.cost_ess * ...
    (p_charge + p_discharge) * 1e-3);
objective_stage2 = settled_grid_cost + cost_carbon + ...
    cost_storage + payment;

diagnostics = optimize(constraints, objective_stage2, cfg.solver);
if diagnostics.problem ~= 0
    error('DCP%d realized Stage 2 求解失败：%s', ...
        dc, yalmiperror(diagnostics.problem));
end

%% ================================== 10 结果提取 ==================================
transfer_cost = calculate_transfer_cost_share( ...
    cfg, dc, stage1_result.consensus_flow);

result.dc = dc;
result.diagnostics = diagnostics;
result.workload_inter_group = workload_inter;
result.workload_batch_group = workload_batch;
result.selected_inter_delay = value(selected_inter_delay);
result.selected_batch_delay = value(selected_batch_delay);
result.adjusted_batch = value(adjusted_batch);
result.payment_inter = value(payment_inter);
result.payment_batch = value(payment_batch);
result.payment = value(payment);
result.server_total = value(server_total);
result.p_it = value(p_it);
result.p_dc_load = value(p_dc_load);
result.p_grid = value(p_grid);
result.p_grid_buy = value(p_grid_buy);
result.p_grid_sell = value(p_grid_sell);
result.p_pv = value(p_pv);
result.p_wind = value(p_wind);
result.p_charge = value(p_charge);
result.p_discharge = value(p_discharge);
result.soc = value(soc);
result.net_power_import = net_power_import;
result.grid_buy_up = value(grid_buy_up);
result.grid_buy_down = value(grid_buy_down);
result.grid_sell_up = value(grid_sell_up);
result.grid_sell_down = value(grid_sell_down);
result.cost_purchase = value(cost_purchase);
result.revenue_sell = value(revenue_sell);
result.cost_grid_imbalance = value(cost_grid_imbalance);
result.cost_carbon = value(cost_carbon);
result.cost_storage = value(cost_storage);
result.stage2_operating_cost = value(objective_stage2);
result.transfer_cost = transfer_cost;
result.end_to_end_cost = result.stage2_operating_cost + transfer_cost;
result.workload_accounting_inter_error = max(abs( ...
    sum(workload_inter, 1) - stage1_result.node{dc}.workload_inter));
result.workload_accounting_batch_error = max(abs( ...
    sum(workload_batch, 1) - stage1_result.node{dc}.workload_batch0));

power_residual = result.p_grid + result.p_pv + result.p_wind + ...
    result.p_discharge - result.p_charge + ...
    result.net_power_import - result.p_dc_load;
if ~cfg.dcp(dc).has_energy
    power_residual = result.p_grid - result.p_dc_load;
end
result.maximum_power_balance_error = max(abs(power_residual));
end

function net_power_import = calculate_net_power_import(cfg, dc, flow)
net_power_import = zeros(1, cfg.number_period);
for t = 1:cfg.number_period
    net_power_import(t) = sum(flow(cfg.map.in_power{dc, t})) - ...
        sum(flow(cfg.map.out_power{dc, t}));
end
end

function transfer_cost = calculate_transfer_cost_share(cfg, dc, flow)
transfer_cost = 0;
incident_links = [cfg.map.out_links{dc}, cfg.map.in_links{dc}];
for ell = incident_links
    if cfg.links(ell).type <= 2
        unit_cost = cfg.cost_workload_transfer;
    else
        unit_cost = cfg.cost_power_transfer;
    end
    transfer_cost = transfer_cost + ...
        0.5 * unit_cost * abs(flow(ell));
end
end

function [inter_group, batch_group] = split_representative_groups( ...
        cfg, dc, stage1_result)
flow = stage1_result.consensus_flow;
incoming_inter = zeros(1, cfg.number_period);
incoming_batch = zeros(1, cfg.number_period);
for t = 1:cfg.number_period
    outgoing_side_inter = flow(cfg.map.out_inter{dc, t});
    outgoing_side_batch = flow(cfg.map.out_batch{dc, t});
    incoming_inter(t) = incoming_inter(t) + ...
        sum(max(-outgoing_side_inter, 0));
    incoming_batch(t) = incoming_batch(t) + ...
        sum(max(-outgoing_side_batch, 0));

    incoming_side_inter = flow(cfg.map.in_inter{dc, t});
    incoming_side_batch = flow(cfg.map.in_batch{dc, t});
    incoming_inter(t) = incoming_inter(t) + ...
        sum(max(incoming_side_inter, 0));
    incoming_batch(t) = incoming_batch(t) + ...
        sum(max(incoming_side_batch, 0));
end

post_inter = stage1_result.node{dc}.workload_inter;
post_batch = stage1_result.node{dc}.workload_batch0;
local_inter = post_inter - incoming_inter;
local_batch = post_batch - incoming_batch;
assert(all(local_inter >= -1e-7) && all(local_batch >= -1e-7), ...
    'DCP%d realized user-group accounting produced negative local load.', dc);
inter_group = [max(local_inter, 0); incoming_inter];
batch_group = [max(local_batch, 0); incoming_batch];
end
