%% R2C8：Location 1 电价敏感性分析（ADMM 正式结果）
% M2 没有跨 DCP 耦合，直接复用独立优化结果；五个 M5 场景采用 ADMM 求解。

clear;
clc;
close all;
yalmip('clear');
total_timer = tic;

%% ================================== 00 环境初始化 ==================================
case_directory = fileparts(mfilename('fullpath'));
project_root = fileparts(case_directory);
common_directory = fullfile(project_root, 'Common_Functions');
centralized_output_directory = fullfile(case_directory, 'outputs');
output_directory = fullfile(case_directory, 'outputs_admm');
original_path = path;
addpath(common_directory, case_directory);
cleanup_path = onCleanup(@() path(original_path));

assert(exist('yalmip', 'file') == 2, '未找到 YALMIP，请先配置 YALMIP 路径。');
assert(exist('gurobi', 'file') ~= 0, '未找到 Gurobi MATLAB 接口。');
if ~isfolder(output_directory)
    mkdir(output_directory);
end

%% ================================== 01 场景设置 ==================================
price_scaling_factors = [0.8, 0.9, 1.0, 1.1, 1.2];                           % Location 1 电价倍率
method_names = "M5";                                                         % 仅耦合场景需要 ADMM 迭代
number_scenario = numel(price_scaling_factors) * numel(method_names);
admm_time_limit_seconds = 1800;                                               % 单个 ADMM 场景时间上限，s

centralized_reference_file = fullfile(centralized_output_directory, ...
    'r2c8_price_sensitivity_results.mat');
assert(isfile(centralized_reference_file), ...
    '缺少集中式参考结果：%s', centralized_reference_file);
reference_data = load(centralized_reference_file, 'detail_table');
centralized_detail_table = reference_data.detail_table;

detail_table = centralized_detail_table(centralized_detail_table.Method == "M2", :);
detail_table.SolutionSource = repmat("Independent M2", height(detail_table), 1);
detail_table.ADMMIterations = nan(height(detail_table), 1);
detail_table.ADMMConverged = nan(height(detail_table), 1);
detail_table.ADMMTerminationReason = repmat("NotApplicable", height(detail_table), 1);
detail_table.ADMMFinalPrimalResidual = nan(height(detail_table), 1);
detail_table.ADMMFinalDualResidual = nan(height(detail_table), 1);
big_m_audit_table = table();                                                   % 每个场景的成本 Big-M 核验
scenario_results = cell(number_scenario, 1);                                  % Stage 1/Stage 2 完整数值结果
scenario_index = 0;

%% ================================== 02 逐场景求解 ==================================
for factor_index = 1:numel(price_scaling_factors)
    price_factor = price_scaling_factors(factor_index);

    for method_index = 1:numel(method_names)
        method_name = method_names(method_index);
        scenario_index = scenario_index + 1;
        scenario_name = sprintf('Price %.1f - %s', price_factor, method_name);
        scenario_output = fullfile(output_directory, ...
            sprintf('factor_%0.1f_%s', price_factor, lower(method_name)));

        fprintf('\n================ %s ================\n', scenario_name);
        scenario_timer = tic;
        cfg = prepare_r2c8_case( ...
            project_root, scenario_output, price_factor, method_name);
        cfg.admm.maximum_wall_time_seconds = admm_time_limit_seconds;

        stage1_result = solve_stage1_admm(cfg);
        save(fullfile(scenario_output, 'admm_stage1.mat'), ...
            'stage1_result', '-v7.3');
        if ~stage1_result.converged
            failed_scenario = struct( ...
                'scenario_name', scenario_name, ...
                'termination_reason', stage1_result.termination_reason, ...
                'iterations', stage1_result.iterations, ...
                'wall_time_seconds', stage1_result.wall_time_seconds, ...
                'final_primal_residual', stage1_result.final_primal_residual, ...
                'final_dual_residual', stage1_result.final_dual_residual);
            save(fullfile(output_directory, 'r2c8_admm_failure_checkpoint.mat'), ...
                'failed_scenario', 'scenario_index', 'scenario_results', '-v7.3');
            error('R2C8:ADMMNotConverged', ...
                '%s 未收敛，终止原因：%s。已保存失败检查点。', ...
                scenario_name, stage1_result.termination_reason);
        end
        current_big_m_audit = audit_r2c8_big_m(cfg, stage1_result, scenario_name);
        big_m_audit_table = [big_m_audit_table; current_big_m_audit]; %#ok<AGROW>

        [stage2_results, stage2_summary] = solve_all_stage2( ...
            cfg, stage1_result, scenario_name);
        quality = summarize_case_quality(cfg, stage1_result, ...
            stage2_results, stage2_summary);
        scenario_wall_time = toc(scenario_timer);

        current_row = table( ...
            price_factor, method_name, stage2_summary.total_operating_cost, ...
            stage2_summary.per_dcp_cost(1), stage2_summary.per_dcp_cost(2), ...
            stage2_summary.per_dcp_cost(3), stage2_summary.per_dcp_cost(4), ...
            stage2_summary.per_dcp_cost(5), stage1_result.total_physical_cost, ...
            stage1_result.wall_time_seconds, stage2_summary.wall_time_seconds, ...
            scenario_wall_time, stage2_summary.maximum_single_dcp_mip_gap, ...
            quality.maximum_workload_accounting_error, ...
            quality.maximum_storage_balance_error, ...
            quality.maximum_power_balance_error, ...
            quality.maximum_initial_soc_error, ...
            quality.maximum_disabled_flow, stage2_summary.all_solved, ...
            'VariableNames', { ...
            'PriceScalingFactor', 'Method', 'TotalCost_USD', ...
            'DCP1Cost_USD', 'DCP2Cost_USD', 'DCP3Cost_USD', ...
            'DCP4Cost_USD', 'DCP5Cost_USD', 'Stage1PhysicalCost_USD', ...
            'Stage1WallTime_s', 'Stage2WallTime_s', 'TotalRuntime_s', ...
            'MaximumStage2MIPGap', 'MaximumWorkloadAccountingError', ...
            'MaximumStorageBalanceError', 'MaximumPowerBalanceError', ...
            'MaximumInitialSOCError', 'MaximumDisabledFlow', 'AllSolved'});
        current_row.SolutionSource = "ADMM";
        current_row.ADMMIterations = stage1_result.iterations;
        current_row.ADMMConverged = double(stage1_result.converged);
        current_row.ADMMTerminationReason = string(stage1_result.termination_reason);
        current_row.ADMMFinalPrimalResidual = stage1_result.final_primal_residual;
        current_row.ADMMFinalDualResidual = stage1_result.final_dual_residual;
        detail_table = [detail_table; current_row]; %#ok<AGROW>

        scenario_results{scenario_index} = struct( ...
            'cfg', cfg, 'stage1', stage1_result, ...
            'stage2', {stage2_results}, 'stage2_summary', stage2_summary, ...
            'quality', quality, 'big_m_audit', current_big_m_audit);

        save(fullfile(output_directory, 'r2c8_admm_checkpoint.mat'), ...
            'price_scaling_factors', 'method_names', 'scenario_index', ...
            'detail_table', 'big_m_audit_table', 'scenario_results', '-v7.3');
    end
end

%% ================================== 03 Response 汇总表 ==================================
summary_table = build_response_summary(price_scaling_factors, detail_table);
centralized_comparison_table = build_centralized_comparison( ...
    detail_table, centralized_detail_table);

baseline_row = summary_table(abs(summary_table.PriceScalingFactor - 1.0) < 1e-12, :);
reference_m5_cost = 5456.58943825814;                                         % 已验收五档/四档集中式 M5
baseline_m5_error = abs(baseline_row.M5TotalCost_USD - reference_m5_cost);
assert(baseline_m5_error <= 1e-3, ...
    'R2C8 基准 M5 与已验收五档/四档结果相差 %.6g USD。', baseline_m5_error);
assert(all(detail_table.AllSolved), 'R2C8 至少一个场景未正常求解。');

%% ================================== 04 导出 CSV 与 MAT ==================================
writetable(summary_table, fullfile(output_directory, ...
    'r2c8_price_sensitivity_admm.csv'));
writetable(detail_table, fullfile(output_directory, ...
    'r2c8_price_sensitivity_admm_details.csv'));
writetable(big_m_audit_table, fullfile(output_directory, ...
    'r2c8_admm_big_m_audit.csv'));
writetable(centralized_comparison_table, fullfile(output_directory, ...
    'r2c8_admm_centralized_comparison.csv'));

total_wall_time_seconds = toc(total_timer);
save(fullfile(output_directory, 'r2c8_price_sensitivity_admm_results.mat'), ...
    'price_scaling_factors', 'method_names', 'summary_table', ...
    'detail_table', 'big_m_audit_table', 'centralized_comparison_table', ...
    'scenario_results', 'admm_time_limit_seconds', ...
    'reference_m5_cost', 'baseline_m5_error', ...
    'total_wall_time_seconds', '-v7.3');

disp(summary_table);
fprintf('\nR2C8 ADMM 运行结束，总用时 %.2f s。\n', total_wall_time_seconds);
fprintf('CSV/MAT 结果目录：%s\n', output_directory);

function summary_table = build_response_summary(price_factors, detail_table)
%BUILD_RESPONSE_SUMMARY 生成可直接用于 response 的电价敏感性表。

number_factor = numel(price_factors);
m2_total_cost = zeros(number_factor, 1);
m5_total_cost = zeros(number_factor, 1);
cooperative_saving = zeros(number_factor, 1);
m5_per_dcp_cost = zeros(number_factor, 5);

for index = 1:number_factor
    factor = price_factors(index);
    factor_rows = abs(detail_table.PriceScalingFactor - factor) < 1e-12;
    m2_row = detail_table(factor_rows & detail_table.Method == "M2", :);
    m5_row = detail_table(factor_rows & detail_table.Method == "M5", :);

    assert(height(m2_row) == 1 && height(m5_row) == 1, ...
        '电价倍率 %.1f 的 M2/M5 结果不完整。', factor);

    m2_total_cost(index) = m2_row.TotalCost_USD;
    m5_total_cost(index) = m5_row.TotalCost_USD;
    cooperative_saving(index) = 100 * ...
        (m2_total_cost(index) - m5_total_cost(index)) / m2_total_cost(index);
    m5_per_dcp_cost(index, :) = [ ...
        m5_row.DCP1Cost_USD, m5_row.DCP2Cost_USD, m5_row.DCP3Cost_USD, ...
        m5_row.DCP4Cost_USD, m5_row.DCP5Cost_USD];
end

summary_table = table( ...
    price_factors(:), m2_total_cost, m5_total_cost, cooperative_saving, ...
    m5_per_dcp_cost(:, 1), m5_per_dcp_cost(:, 2), ...
    m5_per_dcp_cost(:, 3), m5_per_dcp_cost(:, 4), ...
    m5_per_dcp_cost(:, 5), ...
    'VariableNames', { ...
    'PriceScalingFactor', 'M2TotalCost_USD', 'M5TotalCost_USD', ...
    'CooperativeSaving_Percent', 'M5_DCP1Cost_USD', 'M5_DCP2Cost_USD', ...
    'M5_DCP3Cost_USD', 'M5_DCP4Cost_USD', 'M5_DCP5Cost_USD'});
end

function comparison_table = build_centralized_comparison( ...
        detail_table, centralized_detail_table)
%BUILD_CENTRALIZED_COMPARISON 核验正式表中各成本与集中式结果的偏差。

number_row = height(detail_table);
centralized_total = zeros(number_row, 1);
reported_total = detail_table.TotalCost_USD;
per_dcp_relative_error = zeros(number_row, 5);

for index = 1:number_row
    reference_row = centralized_detail_table( ...
        abs(centralized_detail_table.PriceScalingFactor - ...
        detail_table.PriceScalingFactor(index)) < 1e-12 & ...
        centralized_detail_table.Method == detail_table.Method(index), :);
    assert(height(reference_row) == 1, '集中式参考场景匹配失败。');
    centralized_total(index) = reference_row.TotalCost_USD;

    for dc = 1:5
        field_name = sprintf('DCP%dCost_USD', dc);
        per_dcp_relative_error(index, dc) = 100 * abs( ...
            detail_table.(field_name)(index) - reference_row.(field_name)) / ...
            max(abs(reference_row.(field_name)), eps);
    end
end

total_difference = reported_total - centralized_total;
total_relative_error = 100 * abs(total_difference) ./ ...
    max(abs(centralized_total), eps);

comparison_table = table( ...
    detail_table.PriceScalingFactor, detail_table.Method, ...
    detail_table.SolutionSource, centralized_total, reported_total, ...
    total_difference, total_relative_error, ...
    per_dcp_relative_error(:, 1), per_dcp_relative_error(:, 2), ...
    per_dcp_relative_error(:, 3), per_dcp_relative_error(:, 4), ...
    per_dcp_relative_error(:, 5), max(per_dcp_relative_error, [], 2), ...
    'VariableNames', { ...
    'PriceScalingFactor', 'Method', 'SolutionSource', ...
    'CentralizedTotalCost_USD', 'ReportedTotalCost_USD', ...
    'ReportedMinusCentralized_USD', 'TotalRelativeError_Percent', ...
    'DCP1RelativeError_Percent', 'DCP2RelativeError_Percent', ...
    'DCP3RelativeError_Percent', 'DCP4RelativeError_Percent', ...
    'DCP5RelativeError_Percent', 'MaximumPerDCPError_Percent'});
end

function quality = summarize_case_quality(cfg, stage1_result, ...
        stage2_results, stage2_summary)
%SUMMARIZE_CASE_QUALITY 汇总守恒、SOC、电力平衡和禁用交互检查。

maximum_workload_error = 0;
maximum_storage_error = 0;
maximum_power_error = 0;
maximum_initial_soc_error = 0;

for dc = 1:cfg.number_dc
    result = stage2_results{dc};
    maximum_workload_error = max(maximum_workload_error, max([ ...
        result.workload_accounting_inter_error, ...
        result.workload_accounting_batch_error]));

    if cfg.dcp(dc).has_energy
        storage_error = result.soc(2:end) - result.soc(1:end-1) - ...
            cfg.eta_charge * result.p_charge + ...
            result.p_discharge / cfg.eta_discharge;
        power_error = result.p_grid + result.p_pv + result.p_wind + ...
            result.p_discharge - result.p_charge + result.net_power_import - ...
            result.p_dc_load;
        maximum_storage_error = max(maximum_storage_error, ...
            max(abs(storage_error), [], 'all'));
        maximum_initial_soc_error = max(maximum_initial_soc_error, ...
            abs(result.soc(1) - cfg.soc_initial));
    else
        power_error = result.p_grid - result.p_dc_load;
    end
    maximum_power_error = max(maximum_power_error, ...
        max(abs(power_error), [], 'all'));
end

disabled_link_mask = false(cfg.number_links, 1);
if cfg.transfer_workload_upper == 0 && cfg.transfer_workload_lower == 0
    disabled_link_mask = disabled_link_mask | cfg.task_link_mask;
end
if cfg.transfer_power_upper == 0 && cfg.transfer_power_lower == 0
    disabled_link_mask = disabled_link_mask | cfg.power_link_mask;
end

if any(disabled_link_mask)
    maximum_disabled_flow = max(abs( ...
        stage1_result.consensus_flow(disabled_link_mask)), [], 'all');
else
    maximum_disabled_flow = 0;
end

quality.maximum_workload_accounting_error = maximum_workload_error;
quality.maximum_storage_balance_error = maximum_storage_error;
quality.maximum_power_balance_error = maximum_power_error;
quality.maximum_initial_soc_error = maximum_initial_soc_error;
quality.maximum_disabled_flow = maximum_disabled_flow;

assert(stage2_summary.all_solved, 'Stage 2 至少一个 DCP 未正常求解。');
assert(maximum_workload_error <= 1e-5, '负荷会计误差超过 1e-5。');
assert(maximum_storage_error <= 1e-5, '储能能量平衡误差超过 1e-5。');
assert(maximum_power_error <= 1e-5, '电力平衡误差超过 1e-5。');
assert(maximum_initial_soc_error <= 1e-5, '初始 SOC 误差超过 1e-5。');
assert(maximum_disabled_flow <= 1e-6, '被禁用的交互流量不为零。');
end
