function exported = export_response_tables( ...
        cfg, centralized_stage1, proposed_admm, baseline_stage2_summary, ...
        admm_table, big_m_table, sensitivity_details)
%EXPORT_RESPONSE_TABLES 导出 R1-5 与 R2-2 的 Response 表格数据。

%% ================================== 00 R1-5 Stage 1 对比 ==================================
centralized_cost = centralized_stage1.total_physical_cost;
admm_cost = proposed_admm.total_physical_cost;
admm_gap = 100 * (admm_cost - centralized_cost) / centralized_cost;

r1c5_table = table( ...
    ["Centralized Stage 1 benchmark"; "Distributed ADMM Stage 1"], ...
    [centralized_cost; admm_cost], ...
    [NaN; admm_gap], ...
    [NaN; proposed_admm.iterations], ...
    [centralized_stage1.wall_time_seconds; proposed_admm.wall_time_seconds], ...
    [string(centralized_stage1.diagnostics.info); ...
        string(compose('Converged=%d', proposed_admm.converged))], ...
    'VariableNames', { ...
    'Method', ...
    'Stage1OperatingCost_USD', ...
    'RelativeGap_Percent', ...
    'ADMMIterations', ...
    'WallTime_s', ...
    'SolverStatus'});

%% ================================== 01 R1-5 逐 DCP 对比 ==================================
per_dcp_gap = 100 * ...
    (proposed_admm.per_dc_cost - centralized_stage1.per_dc_cost) ./ ...
    abs(centralized_stage1.per_dc_cost);
r1c5_per_dcp_table = table( ...
    (1:cfg.number_dc)', ...
    centralized_stage1.per_dc_cost, ...
    proposed_admm.per_dc_cost, ...
    proposed_admm.per_dc_cost - centralized_stage1.per_dc_cost, ...
    per_dcp_gap, ...
    'VariableNames', { ...
    'DCP', ...
    'CentralizedStage1Cost_USD', ...
    'ADMMStage1Cost_USD', ...
    'ADMMMinusCentralized_USD', ...
    'RelativeDifference_Percent'});

%% ================================== 02 R1-5 成本分项 ==================================
component_names = ["Purchase cost"; "Sell revenue"; "Carbon cost"; ...
    "Storage cost"; "Interaction cost"; "Total operating cost"];
centralized_components = aggregate_stage1_components(centralized_stage1);
admm_components = aggregate_stage1_components(proposed_admm);
r1c5_component_table = table( ...
    component_names, centralized_components, admm_components, ...
    admm_components - centralized_components, ...
    'VariableNames', { ...
    'CostComponent', ...
    'CentralizedStage1_USD', ...
    'ADMMStage1_USD', ...
    'ADMMMinusCentralized_USD'});

%% ================================== 03 R2-2 基准参数 ==================================
parameter_table = table( ...
    ["Initial task penalty"; ...
     "Initial power penalty"; ...
     "Task penalty lower bound"; ...
     "Task penalty upper bound"; ...
     "Power penalty lower bound"; ...
     "Power penalty upper bound"; ...
     "Absolute tolerance"; ...
     "Relative tolerance"; ...
     "Maximum ADMM iterations"; ...
     "Cost Big-M"; ...
     "Time Big-M"; ...
     "Residual-balance threshold"; ...
     "Penalty update multiplier"; ...
     "Penalty update period"], ...
    [cfg.admm.rho_task; ...
     cfg.admm.rho_power; ...
     cfg.admm.rho_task_min; ...
     cfg.admm.rho_task_max; ...
     cfg.admm.rho_power_min; ...
     cfg.admm.rho_power_max; ...
     cfg.admm.absolute_tolerance; ...
     cfg.admm.relative_tolerance; ...
     cfg.admm.max_iteration; ...
     cfg.stage2.big_m_cost; ...
     cfg.stage2.big_m_time; ...
     cfg.admm.residual_balance_mu; ...
     cfg.admm.rho_scale; ...
     cfg.admm.rho_update_period], ...
    ["dimensionless"; "dimensionless"; "dimensionless"; "dimensionless"; ...
     "dimensionless"; "dimensionless"; "dimensionless"; "dimensionless"; ...
     "iteration"; "USD"; "h"; "dimensionless"; "dimensionless"; "iteration"], ...
    'VariableNames', {'Parameter', 'BaselineValue', 'Unit'});

%% ================================== 04 CSV 与 MAT ==================================
writetable(r1c5_table, ...
    fullfile(cfg.output_directory, 'r1c5_stage1_benchmark.csv'));
writetable(r1c5_per_dcp_table, ...
    fullfile(cfg.output_directory, 'r1c5_stage1_per_dcp.csv'));
writetable(r1c5_component_table, ...
    fullfile(cfg.output_directory, 'r1c5_stage1_components.csv'));
writetable(parameter_table, ...
    fullfile(cfg.output_directory, 'r2c2_baseline_parameters.csv'));
writetable(admm_table, ...
    fullfile(cfg.output_directory, 'r2c2_admm_sensitivity.csv'));
writetable(big_m_table, ...
    fullfile(cfg.output_directory, 'r2c2_big_m_sensitivity.csv'));

save(fullfile(cfg.output_directory, 'r1c5_r2c2_complete_results.mat'), ...
    'centralized_stage1', 'proposed_admm', 'baseline_stage2_summary', ...
    'r1c5_table', 'r1c5_per_dcp_table', 'r1c5_component_table', ...
    'parameter_table', 'admm_table', 'big_m_table', ...
    'sensitivity_details', '-v7.3');

exported.r1c5 = r1c5_table;
exported.r1c5_per_dcp = r1c5_per_dcp_table;
exported.r1c5_components = r1c5_component_table;
exported.parameters = parameter_table;
exported.admm_sensitivity = admm_table;
exported.big_m_sensitivity = big_m_table;

disp(r1c5_table);
disp(r1c5_per_dcp_table);
disp(admm_table);
disp(big_m_table);
end

function components = aggregate_stage1_components(stage1_result)
%AGGREGATE_STAGE1_COMPONENTS 汇总五个 DCP 的 Stage 1 成本分项。

purchase = sum(cellfun(@(node) node.cost_purchase, stage1_result.node));
sell = sum(cellfun(@(node) node.revenue_sell, stage1_result.node));
carbon = sum(cellfun(@(node) node.cost_carbon, stage1_result.node));
storage = sum(cellfun(@(node) node.cost_storage, stage1_result.node));
interaction = sum(cellfun(@(node) node.cost_transfer, stage1_result.node));
components = [purchase; sell; carbon; storage; interaction; ...
    stage1_result.total_physical_cost];
end
