function model = build_stage1_dcp(cfg, dc, flow, enforce_unrelated_zero)
%BUILD_STAGE1_DCP 构造一个 DCP 的 Stage 1 本地模型。
%
% 同一函数同时服务于集中式与 ADMM：
%   - 集中式传入全局共享的 flow；
%   - ADMM 传入该 DCP 的本地 flow 副本，并将无关链路固定为零。

if nargin < 4
    enforce_unrelated_zero = false;
end

number_period = cfg.number_period;
number_links = cfg.number_links;
dcp = cfg.dcp(dc);
incident_links = [cfg.map.out_links{dc}, cfg.map.in_links{dc}];

%% ================================== 00 决策变量 ==================================
variables.p_it = sdpvar(1, number_period, 'full');                              % IT 功率，kW
variables.p_dc_load = sdpvar(1, number_period, 'full');                         % 园区总负载，kW
variables.server_inter = sdpvar(1, number_period, 'full');                      % 交互式任务服务器数
variables.server_batch = sdpvar(1, number_period, 'full');                      % 批处理任务服务器数
variables.server_total = sdpvar(1, number_period, 'full');                      % 总活跃服务器数
variables.delta_batch = sdpvar(number_period, number_period, 'full');           % 批处理净调整量，request/s
variables.workload_inter = sdpvar(1, number_period, 'full');                    % 迁移后交互式负载，request/s
variables.workload_batch0 = sdpvar(1, number_period, 'full');                   % 时间调整前批处理负载，request/s
variables.workload_batch = sdpvar(1, number_period, 'full');                    % 时间调整后批处理负载，request/s

variables.p_grid = sdpvar(1, number_period, 'full');                            % 电网净功率，kW
variables.p_grid_buy = sdpvar(1, number_period, 'full');                        % 购电功率，kW
variables.p_grid_sell = sdpvar(1, number_period, 'full');                       % 售电功率，kW
variables.p_pv = sdpvar(1, number_period, 'full');                              % 光伏出力，kW
variables.p_wind = sdpvar(1, number_period, 'full');                            % 风电出力，kW
variables.p_charge = sdpvar(1, number_period, 'full');                          % 储能充电功率，kW
variables.p_discharge = sdpvar(1, number_period, 'full');                       % 储能放电功率，kW
variables.soc = sdpvar(1, number_period + 1, 'full');                           % 储能能量，kWh
variables.abs_incident_flow = sdpvar(numel(incident_links), 1, 'full');         % 相邻链路流量绝对值

constraints = [];

%% ================================== 01 有符号任务迁移 ==================================
% 每条链路只保留一个有符号变量。正值为小编号 DCP -> 大编号 DCP，
% 负值表示反向迁移，因此不施加 flow >= 0。
for t = 1:number_period
    out_inter = sum(flow(cfg.map.out_inter{dc, t}));
    in_inter = sum(flow(cfg.map.in_inter{dc, t}));
    out_batch = sum(flow(cfg.map.out_batch{dc, t}));
    in_batch = sum(flow(cfg.map.in_batch{dc, t}));

    if ~isempty(cfg.map.out_inter{dc, t})
        constraints = [constraints, ...
            out_inter >= -cfg.migration_ratio_inter * dcp.workload_inter_origin(t), ...
            out_inter <=  cfg.migration_ratio_inter * dcp.workload_inter_origin(t)]; %#ok<AGROW>
    end
    if ~isempty(cfg.map.out_batch{dc, t})
        constraints = [constraints, ...
            out_batch >= -cfg.migration_ratio_batch * dcp.workload_batch_origin(t), ...
            out_batch <=  cfg.migration_ratio_batch * dcp.workload_batch_origin(t)]; %#ok<AGROW>
    end

    constraints = [constraints, ...
        variables.workload_inter(t) == dcp.workload_inter_origin(t) - out_inter + in_inter, ...
        variables.workload_batch0(t) == dcp.workload_batch_origin(t) - out_batch + in_batch, ...
        variables.workload_inter(t) >= 0, ...
        variables.workload_batch0(t) >= 0];                                    %#ok<AGROW>
end

for ell = incident_links
    if cfg.links(ell).type <= 2
        constraints = [constraints, ...
            flow(ell) >= cfg.transfer_workload_lower, ...
            flow(ell) <= cfg.transfer_workload_upper];                          %#ok<AGROW>
    else
        constraints = [constraints, ...
            flow(ell) >= cfg.transfer_power_lower, ...
            flow(ell) <= cfg.transfer_power_upper];                             %#ok<AGROW>
    end
end

if enforce_unrelated_zero
    unrelated_links = setdiff(1:number_links, incident_links);
    constraints = [constraints, flow(unrelated_links) == 0];
end

%% ================================== 02 批处理时间调整 ==================================
% delta_batch(source, destination) 使用净调整量表示：
%   对角元素 <= 0，表示从原时段移出的部分；
%   有效未来时段 >= 0，表示移入量；
%   行和为零，未移出的任务自然留在原时段执行。
delay_window = cfg.time_tolerance_batch_original;
for source_time = 1:number_period
    for destination_time = 1:number_period
        if destination_time == source_time
            constraints = [constraints, ...
                variables.delta_batch(source_time, destination_time) >= ...
                    -variables.workload_batch0(source_time), ...
                variables.delta_batch(source_time, destination_time) <= 0];    %#ok<AGROW>
        elseif destination_time > source_time && ...
                destination_time - source_time <= delay_window
            constraints = [constraints, ...
                variables.delta_batch(source_time, destination_time) >= 0, ...
                variables.delta_batch(source_time, destination_time) <= ...
                    variables.workload_batch0(source_time)];                   %#ok<AGROW>
        else
            constraints = [constraints, ...
                variables.delta_batch(source_time, destination_time) == 0];    %#ok<AGROW>
        end
    end
    constraints = [constraints, sum(variables.delta_batch(source_time, :)) == 0]; %#ok<AGROW>
end

constraints = [constraints, ...
    variables.workload_batch == variables.workload_batch0 + sum(variables.delta_batch, 1), ...
    variables.workload_batch >= 0];

%% ================================== 03 服务器与 IT 功率 ==================================
for t = 1:number_period
    minimum_inter_servers = variables.workload_inter(t) / ...
        (cfg.processing_speed_server - 1 / cfg.time_tolerance_inter_original);
    minimum_batch_servers = variables.workload_batch(t) / cfg.processing_speed_server;

    constraints = [constraints, ...
        variables.server_inter(t) >= minimum_inter_servers, ...
        variables.server_inter(t) >= 0, ...
        variables.server_inter(t) <= cfg.number_server, ...
        variables.server_batch(t) >= minimum_batch_servers, ...
        variables.server_batch(t) <= minimum_batch_servers + 1, ...
        variables.server_batch(t) >= 0, ...
        variables.server_batch(t) <= cfg.number_server, ...
        variables.server_total(t) >= variables.server_inter(t) + variables.server_batch(t), ...
        variables.server_total(t) >= 0, ...
        variables.server_total(t) <= cfg.number_server];                       %#ok<AGROW>

    constraints = [constraints, ...
        variables.p_it(t) == cfg.p_idle * variables.server_total(t) + ...
        (cfg.p_peak - cfg.p_idle) / cfg.processing_speed_server * ...
        (variables.workload_inter(t) + variables.workload_batch(t)), ...
        variables.p_dc_load(t) == dcp.pue * variables.p_it(t)];                %#ok<AGROW>
end

%% ================================== 04 电力平衡与储能 ==================================
constraints = [constraints, ...
    variables.p_grid_buy >= 0, ...
    variables.p_grid_sell >= 0, ...
    variables.p_grid == variables.p_grid_buy - variables.p_grid_sell, ...
    variables.p_grid >= cfg.p_grid_lower, ...
    variables.p_grid <= cfg.p_grid_upper];

if dcp.has_energy
    % SOC(1) 表示调度开始前的已知能量。每个 1 h 时段结束后更新到 SOC(t+1)。
    constraints = [constraints, variables.soc(1) == cfg.soc_initial];
    for t = 1:number_period
        out_power = sum(flow(cfg.map.out_power{dc, t}));
        in_power = sum(flow(cfg.map.in_power{dc, t}));

        constraints = [constraints, ...
            variables.p_pv(t) >= 0, ...
            variables.p_pv(t) <= dcp.p_pv_max(t), ...
            variables.p_wind(t) >= 0, ...
            variables.p_wind(t) <= dcp.p_wind_max(t), ...
            variables.p_charge(t) >= 0, ...
            variables.p_charge(t) <= cfg.p_charge_max, ...
            variables.p_discharge(t) >= 0, ...
            variables.p_discharge(t) <= cfg.p_discharge_max, ...
            variables.soc(t + 1) == variables.soc(t) + ...
                cfg.eta_charge * variables.p_charge(t) - ...
                variables.p_discharge(t) / cfg.eta_discharge, ...
            variables.soc(t + 1) >= 0, ...
            variables.soc(t + 1) <= cfg.e_max];                                %#ok<AGROW>

        constraints = [constraints, ...
            variables.p_grid(t) + variables.p_pv(t) + variables.p_wind(t) + ...
            variables.p_discharge(t) + in_power == ...
            variables.p_dc_load(t) + variables.p_charge(t) + out_power];       %#ok<AGROW>
    end
else
    constraints = [constraints, ...
        variables.p_grid == variables.p_dc_load, ...
        variables.p_pv == 0, ...
        variables.p_wind == 0, ...
        variables.p_charge == 0, ...
        variables.p_discharge == 0, ...
        variables.soc == 0];
end

%% ================================== 05 交互成本绝对值 ==================================
for local_index = 1:numel(incident_links)
    ell = incident_links(local_index);
    constraints = [constraints, ...
        variables.abs_incident_flow(local_index) >= flow(ell), ...
        variables.abs_incident_flow(local_index) >= -flow(ell), ...
        variables.abs_incident_flow(local_index) >= 0];                        %#ok<AGROW>
end

objective_transfer = 0;
for local_index = 1:numel(incident_links)
    ell = incident_links(local_index);
    if cfg.links(ell).type <= 2
        unit_cost = cfg.cost_workload_transfer;
    else
        unit_cost = cfg.cost_power_transfer;
    end
    % 一条共享链路由两端各承担 50%，五个本地目标相加后恰为完整链路成本。
    objective_transfer = objective_transfer + ...
        0.5 * unit_cost * variables.abs_incident_flow(local_index);
end

%% ================================== 06 本地物理成本与 epsilon R_i ==================================
objective_purchase = sum(dcp.price_ele .* variables.p_grid_buy * 1e-3);
objective_sell = sum(cfg.price_tariff .* variables.p_grid_sell * 1e-3);
objective_carbon = sum(dcp.carbon_eleprice * variables.p_grid_buy * 1e-3);
objective_storage = sum(cfg.cost_ess * ...
    (variables.p_charge + variables.p_discharge) * 1e-3);

objective_physical = objective_purchase - objective_sell + ...
    objective_carbon + objective_storage + objective_transfer;

objective_regularization = cfg.regularization.weight * ( ...
    sum((variables.p_grid / cfg.regularization.grid_scale).^2) + ...
    sum((variables.workload_batch / cfg.regularization.workload_scale).^2));

for ell = incident_links
    objective_regularization = objective_regularization + ...
        0.5 * cfg.regularization.weight * (flow(ell) / cfg.flow_scale(ell))^2;
end

%% ================================== 07 输出模型对象 ==================================
model.constraints = constraints;
model.objective_physical = objective_physical;
model.objective_regularization = objective_regularization;
model.objective_components.purchase = objective_purchase;
model.objective_components.sell = objective_sell;
model.objective_components.carbon = objective_carbon;
model.objective_components.storage = objective_storage;
model.objective_components.transfer = objective_transfer;
model.variables = variables;
model.incident_links = incident_links;
end
