function result = solve_paper_user_sensitivity(project_root, output_directory)
%% R2C11：Fig. 9 DCP1 独立敏感性分析
% 使用与原 Fig. 7 一致的 DCP1 单园区算例。两类不便系数和其他输入、约束、
% 储能及求解设置均继承 Final_Code_npjRevise 当前确认的参数口径。
% 本程序不使用五 DCP M5 的 ADMM 交互结果，也不允许 DCP 间任务或电力交互。

yalmip('clear');
total_timer = tic;

%% ================================== 00 环境初始化 ==================================
assert(exist('yalmip', 'file') == 2, '未找到 YALMIP，请先配置 YALMIP 路径。');
assert(exist('gurobi', 'file') ~= 0, '未找到 Gurobi MATLAB 接口。');
if ~isfolder(output_directory)
    mkdir(output_directory);
end

%% ================================== 01 场景参数 ==================================
target_dcp = 1;                                                               % 与原 Fig. 7/9 一致的单园区 DCP1
coefficient_factors = [0.8, 0.9, 1.0, 1.1, 1.2];                             % 两类不便系数独立倍率
inter_delay_values = [0.05, 0.10, 0.15, 0.20, 0.25];                         % 交互式最大可选延时，s
batch_delay_values = [1, 2, 4, 6];                                           % 批处理最大可选延时，h
stage2_time_limit_seconds = 300;                                              % DCP1 Stage 2 时间上限，s

[scenario_types, test_values, panel_names] = build_scenario_list( ...
    coefficient_factors, inter_delay_values, batch_delay_values);
number_scenario = numel(scenario_types);
checkpoint_file = fullfile(output_directory, 'r2c11_dcp1_checkpoint.mat');
model_design_id = 'dcp1_current_model_inter0p0035_batch1e5_bigm250_v4';

% DCP1 独立运行：保留当前透明负荷和本地资源，所有 DCP 间流量固定为零。
baseline_cfg = prepare_r2c11_case( ...
    project_root, output_directory, "inter_coefficient", 1.0);
independent_stage1_result = build_independent_stage1_result( ...
    baseline_cfg, target_dcp);

% 每次调用重新求解全部场景；检查点仅用于诊断，不作为本次结果来源。
completed_scenario = 0;
detail_table = table();                                                      % 全部敏感性场景详细结果
big_m_audit_table = table();                                                  % DCP1 成本 Big-M 审计结果
scenario_results = cell(number_scenario, 1);                                  % 各场景完整 Stage 2 数值结果

%% ================================== 02 逐场景求解 ==================================
for scenario_index = (completed_scenario + 1):number_scenario
    sensitivity_type = scenario_types(scenario_index);
    test_value = test_values(scenario_index);
    panel_name = panel_names(scenario_index);
    scenario_name = sprintf('DCP1 %s - %.6g', panel_name, test_value);
    scenario_output = fullfile(output_directory, sprintf('%02d_%s', ...
        scenario_index, sensitivity_type));

    fprintf('\n================ %s ================\n', scenario_name);
    scenario_timer = tic;
    cfg = prepare_r2c11_case( ...
        project_root, scenario_output, sensitivity_type, test_value);
    cfg.solver.gurobi.TimeLimit = stage2_time_limit_seconds;

    current_big_m_audit = audit_r2c11_big_m( ...
        cfg, independent_stage1_result, scenario_name, target_dcp);
    big_m_audit_table = [big_m_audit_table; current_big_m_audit]; %#ok<AGROW>

    fprintf('%s -> DCP%d Stage 2...\n', scenario_name, target_dcp);
    stage2_result = solve_stage2_users( ...
        cfg, target_dcp, independent_stage1_result);
    scenario_wall_time = toc(scenario_timer);
    current_row = summarize_scenario( ...
        cfg, target_dcp, sensitivity_type, panel_name, test_value, ...
        stage2_result, scenario_wall_time);
    detail_table = [detail_table; current_row]; %#ok<AGROW>

    scenario_results{scenario_index} = struct( ...
        'cfg', cfg, ...
        'stage2', stage2_result, ...
        'big_m_audit', current_big_m_audit);

    save(checkpoint_file, ...
        'target_dcp', 'coefficient_factors', 'inter_delay_values', ...
        'batch_delay_values', 'scenario_types', 'test_values', ...
        'panel_names', 'scenario_index', 'detail_table', ...
        'big_m_audit_table', 'scenario_results', ...
        'independent_stage1_result', 'stage2_time_limit_seconds', ...
        'model_design_id', '-v7.3');
end

%% ================================== 03 Origin 直贴数据 ==================================
coefficient_plot_table = build_coefficient_plot_table( ...
    coefficient_factors, detail_table);
delay_plot_table = build_delay_plot_table( ...
    inter_delay_values, batch_delay_values, detail_table);

inter_baseline = select_rows(detail_table, "inter_coefficient", 1.0);
batch_baseline = select_rows(detail_table, "batch_coefficient", 1.0);
baseline_cost_difference = abs( ...
    inter_baseline.DCPOperationCost_USD - ...
    batch_baseline.DCPOperationCost_USD);
baseline_payment_difference = abs( ...
    inter_baseline.TotalUserPayment_USD - ...
    batch_baseline.TotalUserPayment_USD);
assert(baseline_cost_difference <= 1e-3 && ...
    baseline_payment_difference <= 1e-3, ...
    '两类系数敏感性的 1.0 倍 DCP1 基准点不一致。');
assert(all(detail_table.AllSolved), 'R2C11 至少一个 DCP1 场景未正常求解。');

%% ================================== 04 保存 CSV 与 Excel ==================================
coefficient_csv = fullfile(output_directory, ...
    'r2c11_fig9_coefficient_plot.csv');
delay_csv = fullfile(output_directory, ...
    'r2c11_delay_tolerance_plot.csv');
detail_csv = fullfile(output_directory, ...
    'r2c11_sensitivity_details.csv');
big_m_csv = fullfile(output_directory, 'r2c11_big_m_audit.csv');
origin_workbook = fullfile(output_directory, ...
    'r2c11_fig9_origin_data.xlsx');

writetable(coefficient_plot_table, coefficient_csv);
writetable(delay_plot_table, delay_csv);
writetable(detail_table, detail_csv);
writetable(big_m_audit_table, big_m_csv);
write_origin_workbook(origin_workbook, coefficient_plot_table, ...
    delay_plot_table, detail_table, big_m_audit_table, baseline_cfg, ...
    target_dcp, coefficient_factors, inter_delay_values, ...
    batch_delay_values, stage2_time_limit_seconds);

total_wall_time_seconds = toc(total_timer);
save(fullfile(output_directory, 'r2c11_fig9_sensitivity_results.mat'), ...
    'target_dcp', 'coefficient_factors', 'inter_delay_values', ...
    'batch_delay_values', 'coefficient_plot_table', 'delay_plot_table', ...
    'detail_table', 'big_m_audit_table', 'scenario_results', ...
    'independent_stage1_result', 'stage2_time_limit_seconds', ...
    'baseline_cost_difference', 'baseline_payment_difference', ...
    'model_design_id', 'total_wall_time_seconds', '-v7.3');

disp(coefficient_plot_table);
disp(delay_plot_table);
fprintf('\nR2C11 DCP1 运行结束，总用时 %.2f s。\n', total_wall_time_seconds);
fprintf('Origin 直贴 Excel：%s\n', origin_workbook);
fprintf('CSV/MAT 结果目录：%s\n', output_directory);
result.coefficient_plot = coefficient_plot_table;
result.delay_plot = delay_plot_table;
result.details = detail_table;
result.scenario_results = scenario_results;
result.baseline_cfg = baseline_cfg;
end

function [scenario_types, test_values, panel_names] = build_scenario_list( ...
        coefficient_factors, inter_delay_values, batch_delay_values)
%BUILD_SCENARIO_LIST 生成四类 DCP1 独立敏感性场景。

scenario_types = [ ...
    repmat("inter_coefficient", 1, numel(coefficient_factors)), ...
    repmat("batch_coefficient", 1, numel(coefficient_factors)), ...
    repmat("inter_delay_max", 1, numel(inter_delay_values)), ...
    repmat("batch_delay_max", 1, numel(batch_delay_values))]';
test_values = [ ...
    coefficient_factors, coefficient_factors, ...
    inter_delay_values, batch_delay_values]';
panel_names = [ ...
    repmat("Interactive coefficient", 1, numel(coefficient_factors)), ...
    repmat("Batch coefficient", 1, numel(coefficient_factors)), ...
    repmat("Interactive maximum delay", 1, numel(inter_delay_values)), ...
    repmat("Batch maximum delay", 1, numel(batch_delay_values))]';
end

function stage1_result = build_independent_stage1_result(cfg, target_dcp)
%BUILD_INDEPENDENT_STAGE1_RESULT 构造 DCP1 独立运行所需的零交互输入。

stage1_result.method = 'DCP1 independent operation';
stage1_result.converged = true;
stage1_result.consensus_flow = zeros(cfg.number_links, 1);                     % 所有任务/电力交互均为零
stage1_result.node = cell(cfg.number_dc, 1);
stage1_result.node{target_dcp}.workload_inter = ...
    cfg.workload_inter_origin(target_dcp, :);                                  % DCP1 原始交互式负荷
stage1_result.node{target_dcp}.workload_batch0 = ...
    cfg.workload_batch_origin(target_dcp, :);                                  % DCP1 原始批处理负荷
end

function current_row = summarize_scenario(cfg, target_dcp, ...
        sensitivity_type, panel_name, test_value, result, scenario_wall_time)
%SUMMARIZE_SCENARIO 汇总 DCP1 绘图指标和数值检查。

total_inter_workload = sum(result.workload_inter_group, 'all');
total_batch_workload = sum(result.workload_batch_group, 'all');
weighted_inter_delay = sum( ...
    result.selected_inter_delay .* result.workload_inter_group, 'all') / ...
    max(total_inter_workload, eps);
weighted_batch_delay = sum( ...
    result.selected_batch_delay .* result.workload_batch_group, 'all') / ...
    max(total_batch_workload, eps);

if cfg.dcp(target_dcp).has_energy
    storage_error = result.soc(2:end) - result.soc(1:end-1) - ...
        cfg.eta_charge * result.p_charge + ...
        result.p_discharge / cfg.eta_discharge;
    power_error = result.p_grid + result.p_pv + result.p_wind + ...
        result.p_discharge - result.p_charge + result.net_power_import - ...
        result.p_dc_load;
    maximum_storage_error = max(abs(storage_error), [], 'all');
    initial_soc_error = abs(result.soc(1) - cfg.soc_initial);
else
    power_error = result.p_grid - result.p_dc_load;
    maximum_storage_error = 0;
    initial_soc_error = 0;
end

maximum_workload_error = max([ ...
    result.workload_accounting_inter_error, ...
    result.workload_accounting_batch_error]);
maximum_power_error = max(abs(power_error), [], 'all');
mip_gap = extract_mip_gap(result.diagnostics);
all_solved = result.diagnostics.problem == 0;

current_row = table( ...
    string(sensitivity_type), string(panel_name), target_dcp, test_value, ...
    result.end_to_end_cost, result.stage2_operating_cost, ...
    result.transfer_cost, result.payment, result.payment_inter, ...
    result.payment_batch, weighted_inter_delay, weighted_batch_delay, ...
    scenario_wall_time, mip_gap, maximum_workload_error, ...
    maximum_storage_error, maximum_power_error, initial_soc_error, all_solved, ...
    'VariableNames', { ...
    'SensitivityType', 'PanelName', 'DCP', 'TestValue', ...
    'DCPOperationCost_USD', 'Stage2LocalCost_USD', ...
    'TransferCost_USD', 'TotalUserPayment_USD', ...
    'InteractivePayment_USD', 'BatchPayment_USD', ...
    'WorkloadWeightedInterDelay_s', 'WorkloadWeightedBatchDelay_h', ...
    'Stage2WallTime_s', 'Stage2MIPGap', 'MaximumWorkloadAccountingError', ...
    'MaximumStorageBalanceError', 'MaximumPowerBalanceError', ...
    'MaximumInitialSOCError', 'AllSolved'});
end

function plot_table = build_coefficient_plot_table(factors, detail_table)
%BUILD_COEFFICIENT_PLOT_TABLE 按两个 Origin 子图的列顺序组织结果。

inter_rows = select_rows(detail_table, "inter_coefficient", factors);
batch_rows = select_rows(detail_table, "batch_coefficient", factors);
plot_table = table( ...
    factors(:), inter_rows.DCPOperationCost_USD, ...
    inter_rows.TotalUserPayment_USD, factors(:), ...
    batch_rows.DCPOperationCost_USD, batch_rows.TotalUserPayment_USD, ...
    'VariableNames', { ...
    'InterCoefficientFactor', 'Inter_DCP_OperationCost_USD', ...
    'Inter_UserPayment_USD', 'BatchCoefficientFactor', ...
    'Batch_DCP_OperationCost_USD', 'Batch_UserPayment_USD'});
end

function plot_table = build_delay_plot_table( ...
        inter_delay_values, batch_delay_values, detail_table)
%BUILD_DELAY_PLOT_TABLE 按两个 Origin 子图的列顺序组织最大可选延时结果。

inter_rows = select_rows(detail_table, "inter_delay_max", inter_delay_values);
batch_rows = select_rows(detail_table, "batch_delay_max", batch_delay_values);
number_row = max(numel(inter_delay_values), numel(batch_delay_values));
batch_x = nan(number_row, 1);
batch_cost = nan(number_row, 1);
batch_payment = nan(number_row, 1);
batch_x(1:numel(batch_delay_values)) = batch_delay_values(:);
batch_cost(1:numel(batch_delay_values)) = batch_rows.DCPOperationCost_USD;
batch_payment(1:numel(batch_delay_values)) = ...
    batch_rows.TotalUserPayment_USD;

plot_table = table( ...
    inter_delay_values(:), inter_rows.DCPOperationCost_USD, ...
    inter_rows.TotalUserPayment_USD, batch_x, batch_cost, batch_payment, ...
    'VariableNames', { ...
    'MaximumInterDelay_s', 'Inter_DCP_OperationCost_USD', ...
    'Inter_UserPayment_USD', 'MaximumBatchDelay_h', ...
    'Batch_DCP_OperationCost_USD', 'Batch_UserPayment_USD'});
end

function selected_rows = select_rows(detail_table, sensitivity_type, values)
%SELECT_ROWS 按指定测试值顺序提取场景结果。

selected_rows = detail_table([],:);
for index = 1:numel(values)
    current_row = detail_table( ...
        detail_table.SensitivityType == sensitivity_type & ...
        abs(detail_table.TestValue - values(index)) <= 1e-12, :);
    assert(height(current_row) == 1, ...
        '%s 的测试值 %.6g 结果数量不是 1。', sensitivity_type, values(index));
    selected_rows = [selected_rows; current_row]; %#ok<AGROW>
end
end

function gap = extract_mip_gap(diagnostics)
%EXTRACT_MIP_GAP 兼容提取 Gurobi 返回的 MIP gap。

gap = NaN;
if ~isfield(diagnostics, 'solveroutput') || ...
        ~isstruct(diagnostics.solveroutput)
    return;
end

solver_output = diagnostics.solveroutput;
if isfield(solver_output, 'result') && isstruct(solver_output.result)
    solver_output = solver_output.result;
end

candidate_fields = {'mipgap', 'MIPGap', 'mipGap'};
for index = 1:numel(candidate_fields)
    field_name = candidate_fields{index};
    if isfield(solver_output, field_name)
        gap = solver_output.(field_name);
        return;
    end
end
end

function write_origin_workbook(workbook_file, coefficient_table, ...
        delay_table, detail_table, big_m_table, cfg, target_dcp, ...
        coefficient_factors, inter_delay_values, batch_delay_values, ...
        time_limit_seconds)
%WRITE_ORIGIN_WORKBOOK 按最终 Origin 工程的四个 Book 生成 A--D 列数据。

if isfile(workbook_file)
    delete(workbook_file);
end

% Origin 工程使用 A-B 绘制运行成本，D-C 绘制用户补偿。
% 因此 Excel 保留物理列顺序 A、B、C、D，其中 D=A+0.01 为第二组曲线横坐标。
inter_coefficient_table = build_origin_four_column_table( ...
    coefficient_table.InterCoefficientFactor, ...
    coefficient_table.Inter_DCP_OperationCost_USD, ...
    coefficient_table.Inter_UserPayment_USD, 'CoefficientFactor');
batch_coefficient_table = build_origin_four_column_table( ...
    coefficient_table.BatchCoefficientFactor, ...
    coefficient_table.Batch_DCP_OperationCost_USD, ...
    coefficient_table.Batch_UserPayment_USD, 'CoefficientFactor');
inter_delay_table = build_origin_four_column_table( ...
    delay_table.MaximumInterDelay_s, ...
    delay_table.Inter_DCP_OperationCost_USD, ...
    delay_table.Inter_UserPayment_USD, 'MaximumInterDelay_s');
batch_delay_table = build_origin_four_column_table( ...
    delay_table.MaximumBatchDelay_h(1:numel(batch_delay_values)), ...
    delay_table.Batch_DCP_OperationCost_USD(1:numel(batch_delay_values)), ...
    delay_table.Batch_UserPayment_USD(1:numel(batch_delay_values)), ...
    'MaximumBatchDelay_h');

writetable(inter_coefficient_table, workbook_file, 'Sheet', 'Book1intercos');
writetable(batch_coefficient_table, workbook_file, 'Sheet', 'Book1batchcos');
writetable(inter_delay_table, workbook_file, 'Sheet', 'Book1intertol');
writetable(batch_delay_table, workbook_file, 'Sheet', 'Book1batchtol');
writetable(detail_table, workbook_file, 'Sheet', 'Scenario_Details');
writetable(big_m_table, workbook_file, 'Sheet', 'BigM_Audit');

parameter_cells = { ...
    'Parameter', 'Value', 'Unit / note'; ...
    'Reviewer comment', 'R2C11', 'Fig. 9 sensitivity'; ...
    'DCP scope', sprintf('DCP%d', target_dcp), 'independent operation'; ...
    'Interactive coefficient baseline', ...
        cfg.stage2.inconvenience_inter(target_dcp), 'current baseline'; ...
    'Batch coefficient baseline', ...
        cfg.stage2.inconvenience_batch(target_dcp), 'current baseline'; ...
    'Coefficient factors', mat2str(coefficient_factors), ...
        'one coefficient varied at a time'; ...
    'Interactive delay candidates', mat2str(inter_delay_values), 's'; ...
    'Batch delay candidates', mat2str(batch_delay_values), 'h'; ...
    'Cost Big-M', cfg.stage2.big_m_cost, 'USD'; ...
    'Time Big-M', cfg.stage2.big_m_time, 'h'; ...
    'Gurobi MIPGap', cfg.solver.gurobi.MIPGap, 'relative gap'; ...
    'Stage 2 time limit', time_limit_seconds, 's per scenario'; ...
    'Reported cost', 'DCP1 operation cost', 'USD'; ...
    'Reported payment', 'payment for computing users', 'USD'};
writecell(parameter_cells, workbook_file, 'Sheet', 'Parameters');
end

function origin_table = build_origin_four_column_table( ...
        x_value, operation_cost, user_payment, x_name)
%BUILD_ORIGIN_FOUR_COLUMN_TABLE 生成 Origin 的 A(X)-B(Y)-C(Y)-D(X) 布局。

x_value = x_value(:);
operation_cost = operation_cost(:);
user_payment = user_payment(:);
shifted_x = x_value + 0.01;                                                   % 与现有 Origin 工程错位规则一致
origin_table = table(x_value, operation_cost, user_payment, shifted_x, ...
    'VariableNames', {x_name, 'OperationCost_USD', ...
    'PaymentForComputingUsers_USD', 'ShiftedX'});
end
