function verification = verify_and_export(cfg, centralized, admm)
%VERIFY_AND_EXPORT 比较 Stage 1 集中式、ADMM 与重构前 V6 基准。

%% ================================== 00 集中式--ADMM 误差 ==================================
total_difference = admm.total_physical_cost - centralized.total_physical_cost;
total_relative_error = 100 * abs(total_difference) / ...
    abs(centralized.total_physical_cost);

per_dc_difference = admm.per_dc_cost - centralized.per_dc_cost;
per_dc_relative_error = 100 * abs(per_dc_difference) ./ ...
    abs(centralized.per_dc_cost);
per_dc_pass = per_dc_relative_error <= cfg.acceptance.admm_per_dc_percent;

per_dc_table = table( ...
    (1:cfg.number_dc)', ...
    centralized.per_dc_cost, ...
    admm.per_dc_cost, ...
    per_dc_difference, ...
    abs(per_dc_difference), ...
    per_dc_relative_error, ...
    per_dc_pass, ...
    'VariableNames', { ...
    'DCP', ...
    'CentralizedCost_USD', ...
    'ADMMCost_USD', ...
    'ADMMMinusCentralized_USD', ...
    'AbsoluteError_USD', ...
    'RelativeError_Percent', ...
    'Within0p1Percent'});

%% ================================== 01 新旧基础模型偏差 ==================================
baseline_difference = centralized.per_dc_cost - cfg.baseline.centralized_per_dc;
baseline_relative_error = 100 * abs(baseline_difference) ./ ...
    abs(cfg.baseline.centralized_per_dc);
baseline_pass = baseline_relative_error <= cfg.acceptance.refactor_percent;

baseline_table = table( ...
    (1:cfg.number_dc)', ...
    cfg.baseline.centralized_per_dc, ...
    centralized.per_dc_cost, ...
    baseline_difference, ...
    baseline_relative_error, ...
    baseline_pass, ...
    'VariableNames', { ...
    'DCP', ...
    'V6BaselineCost_USD', ...
    'FinalCentralizedCost_USD', ...
    'FinalMinusV6_USD', ...
    'RelativeChange_Percent', ...
    'Within1Percent'});

baseline_total_difference = centralized.total_physical_cost - ...
    cfg.baseline.centralized_total;
baseline_total_relative_error = 100 * abs(baseline_total_difference) / ...
    abs(cfg.baseline.centralized_total);

%% ================================== 02 总体验收 ==================================
all_admm_per_dc_pass = all(per_dc_pass);
all_baseline_per_dc_pass = all(baseline_pass);
baseline_total_pass = ...
    baseline_total_relative_error <= cfg.acceptance.refactor_percent;
overall_pass = admm.converged && all_admm_per_dc_pass && ...
    all_baseline_per_dc_pass && baseline_total_pass;

summary_table = table( ...
    centralized.total_physical_cost, ...
    admm.total_physical_cost, ...
    total_difference, ...
    total_relative_error, ...
    max(per_dc_relative_error), ...
    all_admm_per_dc_pass, ...
    cfg.baseline.centralized_total, ...
    baseline_total_difference, ...
    baseline_total_relative_error, ...
    max(baseline_relative_error), ...
    all_baseline_per_dc_pass, ...
    admm.iterations, ...
    admm.converged, ...
    overall_pass, ...
    'VariableNames', { ...
    'CentralizedTotalCost_USD', ...
    'ADMMTotalCost_USD', ...
    'ADMMMinusCentralized_USD', ...
    'TotalRelativeError_Percent', ...
    'MaximumPerDCPError_Percent', ...
    'AllDCPWithin0p1Percent', ...
    'V6BaselineTotalCost_USD', ...
    'FinalMinusV6TotalCost_USD', ...
    'RefactorTotalChange_Percent', ...
    'MaximumRefactorPerDCPChange_Percent', ...
    'AllRefactorDCPWithin1Percent', ...
    'ADMMIterations', ...
    'ADMMConverged', ...
    'OverallPass'});

%% ================================== 03 储能与功率平衡检查 ==================================
storage_table = build_storage_check_table(cfg, centralized, admm);

%% ================================== 04 收敛历史 ==================================
history = admm.history;
convergence_table = table( ...
    history.iteration, ...
    history.physical_cost, ...
    history.augmented_cost, ...
    history.penalty_cost, ...
    history.primal_task, ...
    history.primal_tolerance_task, ...
    history.dual_task, ...
    history.dual_tolerance_task, ...
    history.primal_power, ...
    history.primal_tolerance_power, ...
    history.dual_power, ...
    history.dual_tolerance_power, ...
    history.rho_task, ...
    history.rho_power, ...
    'VariableNames', { ...
    'Iteration', ...
    'PhysicalCost_USD', ...
    'AugmentedObjective', ...
    'PenaltyValue', ...
    'PrimalResidual_Task', ...
    'PrimalTolerance_Task', ...
    'DualResidual_Task', ...
    'DualTolerance_Task', ...
    'PrimalResidual_Power', ...
    'PrimalTolerance_Power', ...
    'DualResidual_Power', ...
    'DualTolerance_Power', ...
    'Rho_Task', ...
    'Rho_Power'});

%% ================================== 05 Fig. 11 各 DCP 收敛数据 ==================================
assert(isfield(history, 'per_dc_physical_cost'), ...
    'ADMM history 缺少 per_dc_physical_cost，请使用更新后的求解程序重新运行。');
assert(max(abs(history.per_dc_physical_cost(end, :)' - admm.per_dc_cost)) <= 1e-6, ...
    'ADMM 最后一轮历史成本与最终 DCP 成本不一致，请检查结果记录逻辑。');
[figure11_origin_table, figure11_audit_table] = ...
    build_figure11_tables(history, centralized);

%% ================================== 06 文件导出 ==================================
writetable(summary_table, fullfile(cfg.output_directory, 'stage1_summary.csv'));
writetable(per_dc_table, fullfile(cfg.output_directory, 'stage1_per_dcp_comparison.csv'));
writetable(baseline_table, fullfile(cfg.output_directory, 'stage1_refactor_baseline.csv'));
writetable(storage_table, fullfile(cfg.output_directory, 'stage1_storage_checks.csv'));
writetable(convergence_table, fullfile(cfg.output_directory, 'stage1_admm_convergence.csv'));
writetable(figure11_origin_table, ...
    fullfile(cfg.output_directory, 'figure11_dcp_convergence.csv'));

%% ================================== 07 Workspace 输出 ==================================
verification.summary = summary_table;
verification.per_dcp = per_dc_table;
verification.refactor_baseline = baseline_table;
verification.storage_checks = storage_table;
verification.convergence = convergence_table;
verification.figure11_origin = figure11_origin_table;
verification.figure11_audit = figure11_audit_table;
verification.overall_pass = overall_pass;
save(fullfile(cfg.output_directory, 'stage1_verification.mat'), ...
    'verification', '-v7.3');

disp(summary_table);
disp(per_dc_table);
disp(baseline_table);
disp(storage_table);

if ~overall_pass
    warning(['验收未通过：请先检查模型逻辑或数值收敛。' ...
        '不要通过盲目调参掩盖差异。']);
end
end

function [origin_table, audit_table] = build_figure11_tables(history, centralized)
%BUILD_FIGURE11_TABLES 生成各 DCP 相对集中式成本误差的 Origin 绘图数据。

number_iteration = numel(history.iteration);
number_dc = numel(centralized.per_dc_cost);
admm_cost_history = history.per_dc_physical_cost;                              % [迭代 x DCP] ADMM 本地成本，USD
centralized_cost_history = repmat(centralized.per_dc_cost(:)', ...
    number_iteration, 1);                                                      % [迭代 x DCP] 集中式参考成本，USD

assert(size(admm_cost_history, 1) == number_iteration && ...
    size(admm_cost_history, 2) == number_dc, ...
    'ADMM 各 DCP 成本历史维度与迭代次数或 DCP 数量不一致。');

absolute_error = abs(admm_cost_history - centralized_cost_history);            % 各 DCP 绝对成本误差，USD
relative_error = absolute_error ./ max(abs(centralized_cost_history), eps);    % 各 DCP 无量纲相对误差

origin_variable_names = cell(1, number_dc + 1);
origin_variable_names{1} = 'Iteration';
for dc = 1:number_dc
    origin_variable_names{dc + 1} = sprintf('DCP%d_RelativeError', dc);
end
origin_table = array2table([history.iteration, relative_error], ...
    'VariableNames', origin_variable_names);

audit_variable_names = cell(1, 3 * number_dc + 1);
audit_variable_names{1} = 'Iteration';
for dc = 1:number_dc
    audit_variable_names{1 + dc} = sprintf('DCP%d_ADMMCost_USD', dc);
    audit_variable_names{1 + number_dc + dc} = ...
        sprintf('DCP%d_CentralizedCost_USD', dc);
    audit_variable_names{1 + 2 * number_dc + dc} = ...
        sprintf('DCP%d_RelativeError', dc);
end
audit_table = array2table([history.iteration, admm_cost_history, ...
    centralized_cost_history, relative_error], ...
    'VariableNames', audit_variable_names);
end

function storage_table = build_storage_check_table(cfg, centralized, admm)
%BUILD_STORAGE_CHECK_TABLE 检查两种求解下相同的初始 SOC、递推式和功率平衡。

method_names = [repmat("Centralized", 3, 1); repmat("ADMM", 3, 1)];
dcp_index = repmat((1:3)', 2, 1);
initial_soc = zeros(6, 1);
initial_soc_error = zeros(6, 1);
maximum_soc_balance_error = zeros(6, 1);
maximum_power_balance_error = zeros(6, 1);

for method_index = 1:2
    if method_index == 1
        method_result = centralized;
    else
        method_result = admm;
    end

    for dc = 1:3
        row = (method_index - 1) * 3 + dc;
        node = method_result.node{dc};
        initial_soc(row) = node.soc(1);
        initial_soc_error(row) = abs(node.soc(1) - cfg.soc_initial);

        soc_residual = node.soc(2:end) - node.soc(1:end-1) - ...
            cfg.eta_charge * node.p_charge + ...
            node.p_discharge / cfg.eta_discharge;
        maximum_soc_balance_error(row) = max(abs(soc_residual));

        if method_index == 1
            flow = centralized.consensus_flow;
        else
            flow = node.flow_local;
        end

        power_residual = zeros(1, cfg.number_period);
        for t = 1:cfg.number_period
            out_power = sum(flow(cfg.map.out_power{dc, t}));
            in_power = sum(flow(cfg.map.in_power{dc, t}));
            power_residual(t) = ...
                node.p_grid(t) + node.p_pv(t) + node.p_wind(t) + ...
                node.p_discharge(t) + in_power - node.p_dc_load(t) - ...
                node.p_charge(t) - out_power;
        end
        maximum_power_balance_error(row) = max(abs(power_residual));
    end
end

storage_table = table( ...
    method_names, ...
    dcp_index, ...
    initial_soc, ...
    initial_soc_error, ...
    maximum_soc_balance_error, ...
    maximum_power_balance_error, ...
    'VariableNames', { ...
    'Method', ...
    'DCP', ...
    'InitialSOC_kWh', ...
    'InitialSOCError_kWh', ...
    'MaximumSOCBalanceError_kWh', ...
    'MaximumPowerBalanceError_kW'});
end
