function verification = verify_stage2_user_logic( ...
        cfg, centralized_result, admm_result)
%VERIFY_STAGE2_USER_LOGIC 验证完整 Stage 2 及端到端成本偏差。
%
% 分别将集中式和 ADMM 的 Stage 1 结果输入同一个 Stage 2 函数，并与
% V6 最终 M5 结果比较。输入结果均由同一入口脚本显式传入。

%% ================================== 00 完整 Stage 2 ==================================
centralized_stage2 = solve_all_dcp(cfg, centralized_result, 'Centralized');
admm_stage2 = solve_all_dcp(cfg, admm_result, 'ADMM');

centralized_cost = extract_vector(centralized_stage2, 'end_to_end_cost');
admm_cost = extract_vector(admm_stage2, 'end_to_end_cost');
baseline_cost = cfg.baseline.final_per_dc;

centralized_vs_baseline = 100 * abs(centralized_cost - baseline_cost) ./ ...
    abs(baseline_cost);
admm_vs_centralized = 100 * abs(admm_cost - centralized_cost) ./ ...
    abs(centralized_cost);

per_dcp_table = table( ...
    (1:cfg.number_dc)', ...
    baseline_cost, ...
    centralized_cost, ...
    admm_cost, ...
    centralized_cost - baseline_cost, ...
    centralized_vs_baseline, ...
    admm_cost - centralized_cost, ...
    admm_vs_centralized, ...
    centralized_vs_baseline <= cfg.acceptance.refactor_percent, ...
    admm_vs_centralized <= cfg.acceptance.admm_per_dc_percent, ...
    'VariableNames', { ...
    'DCP', ...
    'V6FinalCost_USD', ...
    'FinalCentralizedEndToEndCost_USD', ...
    'FinalADMMEndToEndCost_USD', ...
    'FinalCentralizedMinusV6_USD', ...
    'FinalCentralizedVsV6_Percent', ...
    'FinalADMMMinusCentralized_USD', ...
    'FinalADMMVsCentralized_Percent', ...
    'FinalCentralizedWithin1Percent', ...
    'FinalADMMWithin0p1Percent'});

%% ================================== 01 成本分项 ==================================
baseline_component = cfg.baseline.final_components;
component_table = table( ...
    ["V6Final"; "FinalCentralized"; "FinalADMM"], ...
    [baseline_component.interaction; ...
        sum(extract_vector(centralized_stage2, 'transfer_cost')); ...
        sum(extract_vector(admm_stage2, 'transfer_cost'))], ...
    [baseline_component.purchase; ...
        sum(extract_vector(centralized_stage2, 'cost_purchase')); ...
        sum(extract_vector(admm_stage2, 'cost_purchase'))], ...
    [baseline_component.sell; ...
        sum(extract_vector(centralized_stage2, 'revenue_sell')); ...
        sum(extract_vector(admm_stage2, 'revenue_sell'))], ...
    [baseline_component.carbon; ...
        sum(extract_vector(centralized_stage2, 'cost_carbon')); ...
        sum(extract_vector(admm_stage2, 'cost_carbon'))], ...
    [baseline_component.storage; ...
        sum(extract_vector(centralized_stage2, 'cost_storage')); ...
        sum(extract_vector(admm_stage2, 'cost_storage'))], ...
    [baseline_component.payment; ...
        sum(extract_vector(centralized_stage2, 'payment')); ...
        sum(extract_vector(admm_stage2, 'payment'))], ...
    [cfg.baseline.final_total; sum(centralized_cost); sum(admm_cost)], ...
    'VariableNames', { ...
    'Method', ...
    'InteractionCost_USD', ...
    'PurchaseCost_USD', ...
    'SellRevenue_USD', ...
    'CarbonCost_USD', ...
    'StorageCost_USD', ...
    'UserPayment_USD', ...
    'TotalCost_USD'});

%% ================================== 02 负载与储能核查 ==================================
accounting_table = build_accounting_table(cfg, centralized_stage2, admm_stage2);

centralized_total_error = 100 * abs(sum(centralized_cost) - ...
    cfg.baseline.final_total) / abs(cfg.baseline.final_total);
admm_total_error = 100 * abs(sum(admm_cost) - sum(centralized_cost)) / ...
    abs(sum(centralized_cost));
overall_pass = ...
    all(per_dcp_table.FinalCentralizedWithin1Percent) && ...
    all(per_dcp_table.FinalADMMWithin0p1Percent) && ...
    centralized_total_error <= cfg.acceptance.refactor_percent && ...
    admm_total_error <= cfg.acceptance.admm_per_dc_percent;

summary_table = table( ...
    cfg.baseline.final_total, ...
    sum(centralized_cost), ...
    sum(admm_cost), ...
    centralized_total_error, ...
    max(centralized_vs_baseline), ...
    admm_total_error, ...
    max(admm_vs_centralized), ...
    overall_pass, ...
    'VariableNames', { ...
    'V6FinalTotalCost_USD', ...
    'FinalCentralizedEndToEndTotalCost_USD', ...
    'FinalADMMEndToEndTotalCost_USD', ...
    'FinalCentralizedVsV6Total_Percent', ...
    'MaximumFinalCentralizedVsV6PerDCP_Percent', ...
    'FinalADMMVsCentralizedTotal_Percent', ...
    'MaximumFinalADMMVsCentralizedPerDCP_Percent', ...
    'OverallPass'});

%% ================================== 03 导出 ==================================
writetable(summary_table, ...
    fullfile(cfg.output_directory, 'stage2_validation_summary.csv'));
writetable(per_dcp_table, ...
    fullfile(cfg.output_directory, 'stage2_per_dcp_comparison.csv'));
writetable(component_table, ...
    fullfile(cfg.output_directory, 'stage2_cost_components.csv'));
writetable(accounting_table, ...
    fullfile(cfg.output_directory, 'stage2_user_logic_check.csv'));

verification.summary = summary_table;
verification.per_dcp = per_dcp_table;
verification.cost_components = component_table;
verification.accounting = accounting_table;
verification.centralized_stage2 = centralized_stage2;
verification.admm_stage2 = admm_stage2;
verification.overall_pass = overall_pass;
save(fullfile(cfg.output_directory, 'stage2_end_to_end_results.mat'), ...
    'verification', '-v7.3');

disp(summary_table);
disp(per_dcp_table);
disp(component_table);
disp(accounting_table);

if ~overall_pass
    warning(['Stage 2 或端到端验收未通过。请分析 R1C 修改引起的模型差异，' ...
        '不要通过盲目调参缩小偏差。']);
end
end

function results = solve_all_dcp(cfg, stage1_result, method_name)
%SOLVE_ALL_DCP 依次调用同一个 Stage 2 函数求解五个 DCP。

results = cell(cfg.number_dc, 1);
for dc = 1:cfg.number_dc
    fprintf('%s Stage 1 -> DCP%d Stage 2...\n', method_name, dc);
    results{dc} = solve_stage2_users(cfg, dc, stage1_result);
end
end

function values = extract_vector(results, field_name)
%EXTRACT_VECTOR 从五个 DCP 结果中提取同名标量。

values = zeros(numel(results), 1);
for dc = 1:numel(results)
    values(dc) = results{dc}.(field_name);
end
end

function accounting_table = build_accounting_table(cfg, centralized, admm)
%BUILD_ACCOUNTING_TABLE 检查负载闭合、SOC 递推与园区功率平衡。

method = [repmat("Centralized", cfg.number_dc, 1); ...
    repmat("ADMM", cfg.number_dc, 1)];
dcp = repmat((1:cfg.number_dc)', 2, 1);
inter_error = zeros(2 * cfg.number_dc, 1);
batch_error = zeros(2 * cfg.number_dc, 1);
soc_initial_error = zeros(2 * cfg.number_dc, 1);
soc_balance_error = zeros(2 * cfg.number_dc, 1);
power_balance_error = zeros(2 * cfg.number_dc, 1);

for method_index = 1:2
    if method_index == 1
        results = centralized;
    else
        results = admm;
    end

    for dc_index = 1:cfg.number_dc
        row = (method_index - 1) * cfg.number_dc + dc_index;
        result = results{dc_index};
        inter_error(row) = result.workload_accounting_inter_error;
        batch_error(row) = result.workload_accounting_batch_error;

        if cfg.dcp(dc_index).has_energy
            soc_initial_error(row) = abs(result.soc(1) - cfg.soc_initial);
            soc_residual = result.soc(2:end) - result.soc(1:end-1) - ...
                cfg.eta_charge * result.p_charge + ...
                result.p_discharge / cfg.eta_discharge;
            soc_balance_error(row) = max(abs(soc_residual));
        end

        power_residual = result.p_grid + result.p_pv + result.p_wind + ...
            result.p_discharge - result.p_charge + result.net_power_import - ...
            result.p_dc_load;
        power_balance_error(row) = max(abs(power_residual));
    end
end

accounting_table = table( ...
    method, dcp, inter_error, batch_error, soc_initial_error, ...
    soc_balance_error, power_balance_error, ...
    'VariableNames', { ...
    'Stage1Source', ...
    'DCP', ...
    'InteractiveWorkloadAccountingError', ...
    'BatchWorkloadAccountingError', ...
    'InitialSOCError_kWh', ...
    'MaximumSOCBalanceError_kWh', ...
    'MaximumPowerBalanceError_kW'});
end
