%% R2C10：Google/Alibaba 公共 workload trace 交叉验证
% 同一入口生成集中式参考结果和正式汇总结果；M3--M5 同时采用 ADMM 求解。

clear;
clc;
close all;
yalmip('clear');
total_timer = tic;

%% ================================== 00 环境初始化 ==================================
validation_directory = fileparts(mfilename('fullpath'));
project_root = fileparts(validation_directory);
common_directory = fullfile(project_root, 'Common_Functions');
output_directory = fullfile(validation_directory, 'outputs');
original_path = path;
addpath(common_directory, validation_directory);
cleanup_path = onCleanup(@() path(original_path));

assert(exist('yalmip', 'file') == 2, '未找到 YALMIP，请先配置 YALMIP 路径。');
assert(exist('gurobi', 'file') ~= 0, '未找到 Gurobi MATLAB 接口。');
if ~isfolder(output_directory)
    mkdir(output_directory);
end

%% ================================== 01 场景设置 ==================================
trace_names = ["Google", "Alibaba"];
method_names = ["M3", "M4", "M5"];                                         % 有耦合变量的方法
number_scenario = numel(trace_names) * numel(method_names);
admm_time_limit_seconds = 1800;                                               % 单个 ADMM 场景时间上限，s

[centralized_detail_table, centralized_results] = ...
    solve_centralized_references( ...
    project_root, output_directory, validation_directory, trace_names);

detail_table = centralized_detail_table(centralized_detail_table.Method == "M2", :);
detail_table.SolutionSource(:) = "Centralized";
big_m_audit_table = table();                                                   % 每个场景的成本 Big-M 核验
scenario_results = cell(number_scenario, 1);                                  % Stage 1/Stage 2 完整数值结果
generated_workloads = cell(numel(trace_names), 1);                            % 实际送入模型的透明负荷表
scenario_index = 0;

%% ================================== 02 逐场景求解 ==================================
for trace_index = 1:numel(trace_names)
    trace_name = trace_names(trace_index);

    for method_index = 1:numel(method_names)
        method_name = method_names(method_index);
        scenario_index = scenario_index + 1;
        scenario_name = sprintf('%s - %s', trace_name, method_name);
        scenario_output = fullfile(output_directory, ...
            sprintf('%s_%s', lower(trace_name), lower(method_name)));

        fprintf('\n================ %s ================\n', scenario_name);
        scenario_timer = tic;
        [cfg, generated_workload_table, profile_table] = ...
            prepare_r2c10_case(project_root, scenario_output, ...
            validation_directory, trace_name, method_name);
        cfg.admm.maximum_wall_time_seconds = admm_time_limit_seconds;

        if method_index == 1
            generated_workloads{trace_index} = generated_workload_table;
            writetable(generated_workload_table, fullfile(output_directory, ...
                sprintf('r2c10_%s_workload_data.csv', lower(trace_name))));
        end

        stage1_result = solve_stage1_admm(cfg);
        save(fullfile(scenario_output, 'admm_stage1.mat'), ...
            'stage1_result', '-v7.3');
        if ~stage1_result.converged
            failed_scenario = struct( ...
                'scenario_name', scenario_name, ...
                'termination_reason', stage1_result.termination_reason, ...
                'iterations', stage1_result.iterations, ...
                'wall_time_seconds', stage1_result.wall_time_seconds, ...
                'final_primal_residual', stage1_result.final_primal_residual, ...
                'final_dual_residual', stage1_result.final_dual_residual);
            save(fullfile(output_directory, 'r2c10_admm_failure_checkpoint.mat'), ...
                'failed_scenario', 'scenario_index', 'scenario_results', '-v7.3');
            error('R2C10:ADMMNotConverged', ...
                '%s 未收敛，终止原因：%s。已保存失败检查点。', ...
                scenario_name, stage1_result.termination_reason);
        end
        current_big_m_audit = audit_r2c10_big_m(cfg, stage1_result, scenario_name);
        big_m_audit_table = [big_m_audit_table; current_big_m_audit]; %#ok<AGROW>

        [stage2_results, stage2_summary] = solve_all_stage2( ...
            cfg, stage1_result, scenario_name);
        quality = summarize_case_quality(cfg, stage1_result, ...
            stage2_results, stage2_summary);
        scenario_wall_time = toc(scenario_timer);

        current_row = build_trace_detail_row( ...
            trace_name, method_name, stage1_result, stage2_summary, ...
            quality, scenario_wall_time);
        current_row.SolutionSource = "ADMM";
        current_row.ADMMIterations = stage1_result.iterations;
        current_row.ADMMConverged = double(stage1_result.converged);
        current_row.ADMMTerminationReason = string(stage1_result.termination_reason);
        current_row.ADMMFinalPrimalResidual = stage1_result.final_primal_residual;
        current_row.ADMMFinalDualResidual = stage1_result.final_dual_residual;
        detail_table = [detail_table; current_row]; %#ok<AGROW>

        scenario_results{scenario_index} = struct( ...
            'cfg', cfg, 'profile_table', profile_table, ...
            'generated_workload_table', generated_workload_table, ...
            'stage1', stage1_result, 'stage2', {stage2_results}, ...
            'stage2_summary', stage2_summary, 'quality', quality, ...
            'big_m_audit', current_big_m_audit);

        save(fullfile(output_directory, 'r2c10_admm_checkpoint.mat'), ...
            'trace_names', 'method_names', 'scenario_index', ...
            'detail_table', 'big_m_audit_table', 'scenario_results', ...
            'generated_workloads', '-v7.3');
    end
end

%% ================================== 03 Response 汇总表 ==================================
summary_table = build_response_summary(trace_names, detail_table);
centralized_comparison_table = build_centralized_comparison( ...
    detail_table, centralized_detail_table);
assert(all(detail_table.AllSolved), 'R2C10 至少一个场景未正常求解。');

%% ================================== 04 导出 CSV 与 MAT ==================================
writetable(summary_table, fullfile(output_directory, ...
    'r2c10_public_trace_admm_results.csv'));
writetable(detail_table, fullfile(output_directory, ...
    'r2c10_public_trace_admm_details.csv'));
writetable(big_m_audit_table, fullfile(output_directory, ...
    'r2c10_admm_big_m_audit.csv'));
writetable(centralized_comparison_table, fullfile(output_directory, ...
    'r2c10_admm_centralized_comparison.csv'));

total_wall_time_seconds = toc(total_timer);
save(fullfile(output_directory, 'r2c10_public_trace_admm_results.mat'), ...
    'trace_names', 'method_names', 'summary_table', 'detail_table', ...
    'big_m_audit_table', 'centralized_comparison_table', ...
    'scenario_results', 'centralized_results', 'generated_workloads', ...
    'admm_time_limit_seconds', ...
    'total_wall_time_seconds', '-v7.3');

disp(summary_table);
export_reviewer_summary(project_root, 'traces', summary_table);
fprintf('\nR2C10 ADMM 运行结束，总用时 %.2f s。\n', total_wall_time_seconds);
fprintf('CSV/MAT 结果目录：%s\n', output_directory);

function [detail_table, results] = solve_centralized_references( ...
        project_root, output_directory, validation_directory, trace_names)
%SOLVE_CENTRALIZED_REFERENCES 在同一入口内生成 M2--M5 集中式参考结果。

method_names = ["M2", "M3", "M4", "M5"];
number_scenario = numel(trace_names) * numel(method_names);
detail_table = table();
results = cell(number_scenario, 1);
scenario_index = 0;

for trace_index = 1:numel(trace_names)
    trace_name = trace_names(trace_index);
    for method_index = 1:numel(method_names)
        method_name = method_names(method_index);
        scenario_index = scenario_index + 1;
        scenario_name = sprintf('Centralized %s - %s', ...
            trace_name, method_name);
        scenario_output = fullfile(output_directory, 'centralized', ...
            sprintf('%s_%s', lower(trace_name), lower(method_name)));
        scenario_timer = tic;

        [cfg, generated_workload_table, profile_table] = ...
            prepare_r2c10_case(project_root, scenario_output, ...
            validation_directory, trace_name, method_name);
        stage1_result = solve_stage1_centralized(cfg);
        [stage2_results, stage2_summary] = solve_all_stage2( ...
            cfg, stage1_result, scenario_name);
        quality = summarize_case_quality( ...
            cfg, stage1_result, stage2_results, stage2_summary);
        scenario_wall_time = toc(scenario_timer);

        current_row = build_trace_detail_row( ...
            trace_name, method_name, stage1_result, stage2_summary, ...
            quality, scenario_wall_time);
        current_row.SolutionSource = "Centralized";
        current_row.ADMMIterations = NaN;
        current_row.ADMMConverged = NaN;
        current_row.ADMMTerminationReason = "NotApplicable";
        current_row.ADMMFinalPrimalResidual = NaN;
        current_row.ADMMFinalDualResidual = NaN;
        detail_table = [detail_table; current_row];                            %#ok<AGROW>

        results{scenario_index} = struct( ...
            'cfg', cfg, 'profile_table', profile_table, ...
            'generated_workload_table', generated_workload_table, ...
            'stage1', stage1_result, 'stage2', {stage2_results}, ...
            'stage2_summary', stage2_summary, 'quality', quality);
    end
end
end

function current_row = build_trace_detail_row( ...
        trace_name, method_name, stage1_result, stage2_summary, ...
        quality, scenario_wall_time)
%BUILD_TRACE_DETAIL_ROW 统一集中式与 ADMM 结果的明细字段。

current_row = table( ...
    trace_name, method_name, stage2_summary.total_operating_cost, ...
    stage2_summary.per_dcp_cost(1), stage2_summary.per_dcp_cost(2), ...
    stage2_summary.per_dcp_cost(3), stage2_summary.per_dcp_cost(4), ...
    stage2_summary.per_dcp_cost(5), stage1_result.total_physical_cost, ...
    stage1_result.wall_time_seconds, stage2_summary.wall_time_seconds, ...
    scenario_wall_time, stage2_summary.maximum_single_dcp_mip_gap, ...
    quality.maximum_workload_accounting_error, ...
    quality.maximum_storage_balance_error, ...
    quality.maximum_power_balance_error, ...
    quality.maximum_initial_soc_error, quality.maximum_disabled_flow, ...
    stage2_summary.all_solved, ...
    'VariableNames', { ...
    'WorkloadTrace', 'Method', 'TotalCost_USD', ...
    'DCP1Cost_USD', 'DCP2Cost_USD', 'DCP3Cost_USD', ...
    'DCP4Cost_USD', 'DCP5Cost_USD', 'Stage1PhysicalCost_USD', ...
    'Stage1WallTime_s', 'Stage2WallTime_s', 'TotalRuntime_s', ...
    'MaximumStage2MIPGap', 'MaximumWorkloadAccountingError', ...
    'MaximumStorageBalanceError', 'MaximumPowerBalanceError', ...
    'MaximumInitialSOCError', 'MaximumDisabledFlow', 'AllSolved'});
end

function summary_table = build_response_summary(trace_names, detail_table)
%BUILD_RESPONSE_SUMMARY 生成 M2--M5 成本及相对 M2 节约率。

number_trace = numel(trace_names);
method_cost = zeros(number_trace, 4);
method_saving = zeros(number_trace, 3);

for trace_index = 1:number_trace
    trace_name = trace_names(trace_index);
    trace_rows = detail_table.WorkloadTrace == trace_name;

    for method_index = 1:4
        method_name = "M" + string(method_index + 1);
        method_row = detail_table(trace_rows & ...
            detail_table.Method == method_name, :);
        assert(height(method_row) == 1, ...
            '%s 的 %s 结果不完整。', trace_name, method_name);
        method_cost(trace_index, method_index) = method_row.TotalCost_USD;
    end

    method_saving(trace_index, :) = 100 * ...
        (method_cost(trace_index, 1) - method_cost(trace_index, 2:4)) / ...
        method_cost(trace_index, 1);
end

summary_table = table( ...
    trace_names(:), method_cost(:, 1), method_cost(:, 2), ...
    method_cost(:, 3), method_cost(:, 4), ...
    method_saving(:, 1), method_saving(:, 2), method_saving(:, 3), ...
    'VariableNames', { ...
    'WorkloadTrace', 'M2TotalCost_USD', 'M3TotalCost_USD', ...
    'M4TotalCost_USD', 'M5TotalCost_USD', ...
    'M3SavingVsM2_Percent', 'M4SavingVsM2_Percent', ...
    'M5SavingVsM2_Percent'});
end

function comparison_table = build_centralized_comparison( ...
        detail_table, centralized_detail_table)
%BUILD_CENTRALIZED_COMPARISON 核验正式表中各成本与集中式结果的偏差。

number_row = height(detail_table);
centralized_total = zeros(number_row, 1);
reported_total = detail_table.TotalCost_USD;
per_dcp_relative_error = zeros(number_row, 5);

for index = 1:number_row
    reference_row = centralized_detail_table( ...
        centralized_detail_table.WorkloadTrace == ...
        detail_table.WorkloadTrace(index) & ...
        centralized_detail_table.Method == detail_table.Method(index), :);
    assert(height(reference_row) == 1, '集中式参考场景匹配失败。');
    centralized_total(index) = reference_row.TotalCost_USD;

    for dc = 1:5
        field_name = sprintf('DCP%dCost_USD', dc);
        per_dcp_relative_error(index, dc) = 100 * abs( ...
            detail_table.(field_name)(index) - reference_row.(field_name)) / ...
            max(abs(reference_row.(field_name)), eps);
    end
end

total_difference = reported_total - centralized_total;
total_relative_error = 100 * abs(total_difference) ./ ...
    max(abs(centralized_total), eps);

comparison_table = table( ...
    detail_table.WorkloadTrace, detail_table.Method, ...
    detail_table.SolutionSource, centralized_total, reported_total, ...
    total_difference, total_relative_error, ...
    per_dcp_relative_error(:, 1), per_dcp_relative_error(:, 2), ...
    per_dcp_relative_error(:, 3), per_dcp_relative_error(:, 4), ...
    per_dcp_relative_error(:, 5), max(per_dcp_relative_error, [], 2), ...
    'VariableNames', { ...
    'WorkloadTrace', 'Method', 'SolutionSource', ...
    'CentralizedTotalCost_USD', 'ReportedTotalCost_USD', ...
    'ReportedMinusCentralized_USD', 'TotalRelativeError_Percent', ...
    'DCP1RelativeError_Percent', 'DCP2RelativeError_Percent', ...
    'DCP3RelativeError_Percent', 'DCP4RelativeError_Percent', ...
    'DCP5RelativeError_Percent', 'MaximumPerDCPError_Percent'});
end

function quality = summarize_case_quality(cfg, stage1_result, ...
        stage2_results, stage2_summary)
%SUMMARIZE_CASE_QUALITY 汇总守恒、SOC、电力平衡和禁用交互检查。

maximum_workload_error = 0;
maximum_storage_error = 0;
maximum_power_error = 0;
maximum_initial_soc_error = 0;

for dc = 1:cfg.number_dc
    result = stage2_results{dc};
    maximum_workload_error = max(maximum_workload_error, max([ ...
        result.workload_accounting_inter_error, ...
        result.workload_accounting_batch_error]));

    if cfg.dcp(dc).has_energy
        storage_error = result.soc(2:end) - result.soc(1:end-1) - ...
            cfg.eta_charge * result.p_charge + ...
            result.p_discharge / cfg.eta_discharge;
        power_error = result.p_grid + result.p_pv + result.p_wind + ...
            result.p_discharge - result.p_charge + result.net_power_import - ...
            result.p_dc_load;
        maximum_storage_error = max(maximum_storage_error, ...
            max(abs(storage_error), [], 'all'));
        maximum_initial_soc_error = max(maximum_initial_soc_error, ...
            abs(result.soc(1) - cfg.soc_initial));
    else
        power_error = result.p_grid - result.p_dc_load;
    end
    maximum_power_error = max(maximum_power_error, ...
        max(abs(power_error), [], 'all'));
end

disabled_link_mask = false(cfg.number_links, 1);
if cfg.transfer_workload_upper == 0 && cfg.transfer_workload_lower == 0
    disabled_link_mask = disabled_link_mask | cfg.task_link_mask;
end
if cfg.transfer_power_upper == 0 && cfg.transfer_power_lower == 0
    disabled_link_mask = disabled_link_mask | cfg.power_link_mask;
end

if any(disabled_link_mask)
    maximum_disabled_flow = max(abs( ...
        stage1_result.consensus_flow(disabled_link_mask)), [], 'all');
else
    maximum_disabled_flow = 0;
end

quality.maximum_workload_accounting_error = maximum_workload_error;
quality.maximum_storage_balance_error = maximum_storage_error;
quality.maximum_power_balance_error = maximum_power_error;
quality.maximum_initial_soc_error = maximum_initial_soc_error;
quality.maximum_disabled_flow = maximum_disabled_flow;

assert(stage2_summary.all_solved, 'Stage 2 至少一个 DCP 未正常求解。');
assert(maximum_workload_error <= 1e-5, '负荷会计误差超过 1e-5。');
assert(maximum_storage_error <= 1e-5, '储能能量平衡误差超过 1e-5。');
assert(maximum_power_error <= 1e-5, '电力平衡误差超过 1e-5。');
assert(maximum_initial_soc_error <= 1e-5, '初始 SOC 误差超过 1e-5。');
assert(maximum_disabled_flow <= 1e-6, '被禁用的交互流量不为零。');
end
